### ISSUE TITLE
AudioBoom error

### ISSUE THREAD

**Issue by Whichcraft** [smicallef/spiderfoot#103]
127.0.0.1 - - [22/Aug/2016:11:38:00] "POST /scaneventresults HTTP/1.1" 200 15174 "http://127.0.0.1:5001/scaninfo?id=450f0b9a57f3ed0dfe258d55c916ae993bc9b2bc850fd43c937db3de07266be7" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:48.0) Gecko/20100101 Firefox/48.0"
Exception in thread sfp_accounts_AudioBoom:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/opt/spiderfoot-2.7.0/modules/sfp_accounts.py", line 107, in checkSite
    if site['account_missing_string'] in res['content']:
TypeError: coercing to Unicode: need string or buffer, list found

Always when AudioBoom ist called.

**Comment by smicallef** [comment]
This is now fixed on github and will be in the upcoming 2.7.1 release in a few days.
