### ISSUE TITLE
Issue running Kali Rolling 2016.2

### ISSUE THREAD

**Issue by jteslaxxx** [smicallef/spiderfoot#106]
Hello!

It seems there is some problem running Spiderfoot latest (2.7) on Kali Linux Rolling 2016.2! I installed all dependencies, tried to run ./sf.py and getting error with m2crypto! Tried uninstall it and reinstall! Manually went through all installation process! Here is output:
root@kali:/opt/pentest/RECON/spiderfoot-2.7.0# ./sf.py

Critical Start-up Failure: /usr/local/lib/python2.7/dist-packages/M2Crypto/__m2crypto.so: undefined symbol: SSLv3_method
=================================
It appears you are missing a module required for SpiderFoot
to function. Please refer to the documentation for the list
of dependencies and install them.

Python modules required are: 
 - M2Crypto
 - netaddr
 - dns
 - cherrypy
 - mako
 - socks
 - pyPdf
 - metapdf
 - openxmllib
 - stem
 - bs4
 - gexf
 - phonenumbers

If you are running on Windows and getting this error, please
report this as a bug to support@spiderfoot.net.
root@kali:~# pip install netaddr
Requirement already satisfied (use --upgrade to upgrade): netaddr in /usr/lib/python2.7/dist-packages
root@kali:~# apt-get install python-dns
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python-dns is already the newest version (2.3.6-3).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
root@kali:~# pip install cherrypy
Requirement already satisfied (use --upgrade to upgrade): cherrypy in /usr/local/lib/python2.7/dist-packages
Requirement already satisfied (use --upgrade to upgrade): six in /usr/lib/python2.7/dist-packages (from cherrypy)
root@kali:~# apt-get install --upgrade python-dns
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python-dns is already the newest version (2.3.6-3).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
root@kali:~# pip install mako
Requirement already satisfied (use --upgrade to upgrade): mako in /usr/lib/python2.7/dist-packages
root@kali:~# apt-get install --upgrade python-socks
E: Could not get lock /var/lib/dpkg/lock - open (11: Resource temporarily unavailable)
E: Unable to lock the administration directory (/var/lib/dpkg/), is another process using it?
root@kali:~# apt-get install --upgrade python-socks
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python-socks is already the newest version (1.5.7+dfsg1-1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
root@kali:~# apt-get install --upgrade python-pyPdf
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package python-pyPdf
root@kali:~# apt-get install --upgrade python-pypdf
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python-pypdf is already the newest version (1:1.13-3).
python-pypdf set to manually installed.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
root@kali:~# apt-get install --upgrade python-metapdf
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package python-metapdf
root@kali:~# pip install metapdf
Requirement already satisfied (use --upgrade to upgrade): metapdf in /usr/local/lib/python2.7/dist-packages
Requirement already satisfied (use --upgrade to upgrade): pyPdf in /usr/lib/python2.7/dist-packages (from metapdf)
root@kali:~# pip install openxmllib
Requirement already satisfied (use --upgrade to upgrade): openxmllib in /usr/local/lib/python2.7/dist-packages
Requirement already satisfied (use --upgrade to upgrade): lxml>=3.4.0 in /usr/local/lib/python2.7/dist-packages (from openxmllib)
root@kali:~# pip install stem
Requirement already satisfied (use --upgrade to upgrade): stem in /usr/local/lib/python2.7/dist-packages
root@kali:~# pip install bs4
Requirement already satisfied (use --upgrade to upgrade): bs4 in /usr/local/lib/python2.7/dist-packages
Requirement already satisfied (use --upgrade to upgrade): beautifulsoup4 in /usr/lib/python2.7/dist-packages (from bs4)
root@kali:~# pip install gexf
Collecting gexf
  Could not find a version that satisfies the requirement gexf (from versions: )
No matching distribution found for gexf
root@kali:~# apt-get install --upgrade python-gefx
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package python-gefx
root@kali:~# apt-get install --upgrade python-gexf
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package python-gexf
root@kali:~# locate gefx
root@kali:~# locate python-gefx
root@kali:~# pip install simplegexf 
Collecting simplegexf
  Downloading simplegexf-0.1.5.tar.gz
Collecting xmltodict==0.9.2 (from simplegexf)
  Downloading xmltodict-0.9.2.tar.gz
Building wheels for collected packages: simplegexf, xmltodict
  Running setup.py bdist_wheel for simplegexf ... done
  Stored in directory: /root/.cache/pip/wheels/12/6c/3e/280346a438b686bd74a85936bd153c7e9b616dd91db2355474
  Running setup.py bdist_wheel for xmltodict ... done
  Stored in directory: /root/.cache/pip/wheels/45/a2/7c/951293f71ff0bf42442268cbd0b24b70518e11d98591221552
Successfully built simplegexf xmltodict
Installing collected packages: xmltodict, simplegexf
Successfully installed simplegexf-0.1.5 xmltodict-0.9.2
root@kali:~# pip install phonenumbers
Requirement already satisfied (use --upgrade to upgrade): phonenumbers in /usr/local/lib/python2.7/dist-packages
root@kali:~# pip install -e git+https://github.com/Hypernode/m2crypto#egg=M2Crypto
Obtaining M2Crypto from git+https://github.com/Hypernode/m2crypto#egg=M2Crypto
  Cloning https://github.com/Hypernode/m2crypto to ./src/m2crypto
Installing collected packages: M2Crypto
  Running setup.py develop for M2Crypto
    Complete output from command /usr/bin/python -c "import setuptools, tokenize;__file__='/root/src/m2crypto/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" develop --no-deps:
    running develop
    running egg_info
    writing M2Crypto.egg-info/PKG-INFO
    writing top-level names to M2Crypto.egg-info/top_level.txt
    writing dependency_links to M2Crypto.egg-info/dependency_links.txt
    warning: manifest_maker: standard file '-c' not found
    
    reading manifest file 'M2Crypto.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no previously-included files found matching 'M2Crypto/_m2crypto.py'
    writing manifest file 'M2Crypto.egg-info/SOURCES.txt'
    running build_ext
    building 'M2Crypto.__m2crypto' extension
    swigging SWIG/_m2crypto.i to SWIG/_m2crypto_wrap.c
    swig -python -I/usr/include/python2.7 -I/usr/include -includeall -modern -builtin -outdir build/lib.linux-x86_64-2.7/M2Crypto -o SWIG/_m2crypto_wrap.c SWIG/_m2crypto.i
    unable to execute 'swig': No such file or directory
    error: command 'swig' failed with exit status 1
    
    ----------------------------------------
Command "/usr/bin/python -c "import setuptools, tokenize;__file__='/root/src/m2crypto/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" develop --no-deps" failed with error code 1 in /root/src/m2crypto/
root@kali:~# pip uninstall m2crypto
Uninstalling M2Crypto-0.25.1:
  /usr/local/lib/python2.7/dist-packages/M2Crypto-0.25.1.dist-info/DESCRIPTION.rst
  /usr/local/lib/python2.7/dist-packages/M2Crypto-0.25.1.dist-info/INSTALLER
  /usr/local/lib/python2.7/dist-packages/M2Crypto-0.25.1.dist-info/METADATA
  /usr/local/lib/python2.7/dist-packages/M2Crypto-0.25.1.dist-info/RECORD
  /usr/local/lib/python2.7/dist-packages/M2Crypto-0.25.1.dist-info/WHEEL
  /usr/local/lib/python2.7/dist-packages/M2Crypto-0.25.1.dist-info/metadata.json
  /usr/local/lib/python2.7/dist-packages/M2Crypto-0.25.1.dist-info/top_level.txt
  /usr/local/lib/python2.7/dist-packages/M2Crypto/ASN1.py
  /usr/local/lib/python2.7/dist-packages/M2Crypto/ASN1.pyc
  /usr/local/lib/python2.7/dist-packages/M2Crypto/AuthCookie.py
  /usr/local/lib/python2.7/dist-packages/M2Crypto/AuthCookie.pyc
  /usr/local/lib/python2.7/dist-packages/M2Crypto/BIO.py
  /usr/local/lib/python2.7/dist-packages/M2Crypto/BIO.pyc
  /usr/local/lib/python2.7/dist-packages/M2Crypto/BN.py
  /usr/local/lib/python2.7/dist-packages/M2Crypto/BN.pyc
  /usr/local/lib/python2.7/dist-packages/M2Crypto/DH.py
  /usr/local/lib/python2.7/dist-packages/M2Crypto/DH.pyc
  /usr/local/lib/python2.7/dist-packages/M2Crypto/DSA.py
  /usr/local/lib/python2.7/dist-packages/M2Crypto/DSA.pyc
  /usr/local/lib/python2.7/dist-packages/M2Crypto/EC.py
  /usr/local/lib/python2.7/dist-packages/M2Crypto/EC.pyc
  /usr/local/lib/python2.7/dist-packages/M2Crypto/EVP.py
  /usr/local/lib/python2.7/dist-packages/M2Crypto/EVP.pyc
  /usr/local/lib/python2.7/dist-packages/M2Crypto/Engine.py
  /usr/local/lib/python2.7/dist-packages/M2Crypto/Engine.pyc
  /usr/local/lib/python2.7/dist-packages/M2Crypto/Err.py
  /usr/local/lib/python2.7/dist-packages/M2Crypto/Err.pyc
  /usr/local/lib/python2.7/dist-packages/M2Crypto/PGP/PublicKey.py
  /usr/local/lib/python2.7/dist-packages/M2Crypto/PGP/PublicKey.pyc
  /usr/local/lib/python2.7/dist-packages/M2Crypto/PGP/PublicKeyRing.py
  /usr/local/lib/python2.7/dist-packages/M2Crypto/PGP/PublicKeyRing.pyc
  /usr/local/lib/python2.7/dist-packages/M2Crypto/PGP/RSA.py
  /usr/local/lib/python2.7/dist-packages/M2Crypto/PGP/RSA.pyc
  /usr/local/lib/python2.7/dist-packages/M2Crypto/PGP/__init__.py
  /usr/local/lib/python2.7/dist-packages/M2Crypto/PGP/__init__.pyc
  /usr/local/lib/python2.7/dist-packages/M2Crypto/PGP/constants.py
  /usr/local/lib/python2.7/dist-packages/M2Crypto/PGP/constants.pyc
  /usr/local/lib/python2.7/dist-packages/M2Crypto/PGP/packet.py
  /usr/local/lib/python2.7/dist-packages/M2Crypto/PGP/packet.pyc
  /usr/local/lib/python2.7/dist-packages/M2Crypto/RC4.py
  /usr/local/lib/python2.7/dist-packages/M2Crypto/RC4.pyc
  /usr/local/lib/python2.7/dist-packages/M2Crypto/RSA.py
  /usr/local/lib/python2.7/dist-packages/M2Crypto/RSA.pyc
  /usr/local/lib/python2.7/dist-packages/M2Crypto/Rand.py
  /usr/local/lib/python2.7/dist-packages/M2Crypto/Rand.pyc
  /usr/local/lib/python2.7/dist-packages/M2Crypto/SMIME.py
  /usr/local/lib/python2.7/dist-packages/M2Crypto/SMIME.pyc
  /usr/local/lib/python2.7/dist-packages/M2Crypto/SSL/Checker.py
  /usr/local/lib/python2.7/dist-packages/M2Crypto/SSL/Checker.pyc
  /usr/local/lib/python2.7/dist-packages/M2Crypto/SSL/Cipher.py
  /usr/local/lib/python2.7/dist-packages/M2Crypto/SSL/Cipher.pyc
  /usr/local/lib/python2.7/dist-packages/M2Crypto/SSL/Connection.py
  /usr/local/lib/python2.7/dist-packages/M2Crypto/SSL/Connection.pyc
  /usr/local/lib/python2.7/dist-packages/M2Crypto/SSL/Context.py
  /usr/local/lib/python2.7/dist-packages/M2Crypto/SSL/Context.pyc
  /usr/local/lib/python2.7/dist-packages/M2Crypto/SSL/SSLServer.py
  /usr/local/lib/python2.7/dist-packages/M2Crypto/SSL/SSLServer.pyc
  /usr/local/lib/python2.7/dist-packages/M2Crypto/SSL/Session.py
  /usr/local/lib/python2.7/dist-packages/M2Crypto/SSL/Session.pyc
  /usr/local/lib/python2.7/dist-packages/M2Crypto/SSL/TwistedProtocolWrapper.py
  /usr/local/lib/python2.7/dist-packages/M2Crypto/SSL/TwistedProtocolWrapper.pyc
  /usr/local/lib/python2.7/dist-packages/M2Crypto/SSL/__init__.py
  /usr/local/lib/python2.7/dist-packages/M2Crypto/SSL/__init__.pyc
  /usr/local/lib/python2.7/dist-packages/M2Crypto/SSL/cb.py
  /usr/local/lib/python2.7/dist-packages/M2Crypto/SSL/cb.pyc
  /usr/local/lib/python2.7/dist-packages/M2Crypto/SSL/ssl_dispatcher.py
  /usr/local/lib/python2.7/dist-packages/M2Crypto/SSL/ssl_dispatcher.pyc
  /usr/local/lib/python2.7/dist-packages/M2Crypto/SSL/timeout.py
  /usr/local/lib/python2.7/dist-packages/M2Crypto/SSL/timeout.pyc
  /usr/local/lib/python2.7/dist-packages/M2Crypto/X509.py
  /usr/local/lib/python2.7/dist-packages/M2Crypto/X509.pyc
  /usr/local/lib/python2.7/dist-packages/M2Crypto/__init__.py
  /usr/local/lib/python2.7/dist-packages/M2Crypto/__init__.pyc
  /usr/local/lib/python2.7/dist-packages/M2Crypto/__m2crypto.so
  /usr/local/lib/python2.7/dist-packages/M2Crypto/_m2crypto.py
  /usr/local/lib/python2.7/dist-packages/M2Crypto/_m2crypto.pyc
  /usr/local/lib/python2.7/dist-packages/M2Crypto/callback.py
  /usr/local/lib/python2.7/dist-packages/M2Crypto/callback.pyc
  /usr/local/lib/python2.7/dist-packages/M2Crypto/ftpslib.py
  /usr/local/lib/python2.7/dist-packages/M2Crypto/ftpslib.pyc
  /usr/local/lib/python2.7/dist-packages/M2Crypto/httpslib.py
  /usr/local/lib/python2.7/dist-packages/M2Crypto/httpslib.pyc
  /usr/local/lib/python2.7/dist-packages/M2Crypto/m2.py
  /usr/local/lib/python2.7/dist-packages/M2Crypto/m2.pyc
  /usr/local/lib/python2.7/dist-packages/M2Crypto/m2urllib.py
  /usr/local/lib/python2.7/dist-packages/M2Crypto/m2urllib.pyc
  /usr/local/lib/python2.7/dist-packages/M2Crypto/m2urllib2.py
  /usr/local/lib/python2.7/dist-packages/M2Crypto/m2urllib2.pyc
  /usr/local/lib/python2.7/dist-packages/M2Crypto/m2xmlrpclib.py
  /usr/local/lib/python2.7/dist-packages/M2Crypto/m2xmlrpclib.pyc
  /usr/local/lib/python2.7/dist-packages/M2Crypto/six.py
  /usr/local/lib/python2.7/dist-packages/M2Crypto/six.pyc
  /usr/local/lib/python2.7/dist-packages/M2Crypto/threading.py
  /usr/local/lib/python2.7/dist-packages/M2Crypto/threading.pyc
  /usr/local/lib/python2.7/dist-packages/M2Crypto/util.py
  /usr/local/lib/python2.7/dist-packages/M2Crypto/util.pyc
Proceed (y/n)? y
  Successfully uninstalled M2Crypto-0.25.1
root@kali:~# apt-get install python-m2crypto
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python-m2crypto is already the newest version (0.24.0-1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
root@kali:~# apt-get remove python-m2crypto
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages will be REMOVED:
  kali-linux-full python-m2crypto python-symmetric-jsonrpc sslcaudit
0 upgraded, 0 newly installed, 4 to remove and 0 not upgraded.
After this operation, 1,850 kB disk space will be freed.
Do you want to continue? [Y/n] y
(Reading database ... 398467 files and directories currently installed.)
Removing kali-linux-full (2016.2.12) ...
Removing sslcaudit (1.0-1kali0) ...
Removing python-symmetric-jsonrpc (0.1-0kali2) ...
Removing python-m2crypto (0.24.0-1) ...
root@kali:~# apt-get install python-m2crypto
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following NEW packages will be installed:
  python-m2crypto
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 171 kB of archives.
After this operation, 864 kB of additional disk space will be used.
Get:1 http://mirrors.netix.net/kali kali-rolling/main amd64 python-m2crypto amd64 0.24.0-1 [171 kB]
Fetched 171 kB in 1s (136 kB/s)         
Selecting previously unselected package python-m2crypto.
(Reading database ... 398281 files and directories currently installed.)
Preparing to unpack .../python-m2crypto_0.24.0-1_amd64.deb ...
Unpacking python-m2crypto (0.24.0-1) ...
Setting up python-m2crypto (0.24.0-1) ...
root@kali:~# pip install m2crypto
Requirement already satisfied (use --upgrade to upgrade): m2crypto in /usr/lib/python2.7/dist-packages
root@kali:~# pip uninstall m2crypto
Not uninstalling m2crypto at /usr/lib/python2.7/dist-packages, outside environment /usr
root@kali:~# apt-get remove python-m2crypto
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages will be REMOVED:
  python-m2crypto
0 upgraded, 0 newly installed, 1 to remove and 0 not upgraded.
After this operation, 864 kB disk space will be freed.
Do you want to continue? [Y/n] y
(Reading database ... 398345 files and directories currently installed.)
Removing python-m2crypto (0.24.0-1) ...
root@kali:~# pip install lxml netaddr M2Crypto cherrypy mako
Requirement already satisfied (use --upgrade to upgrade): lxml in /usr/local/lib/python2.7/dist-packages
Requirement already satisfied (use --upgrade to upgrade): netaddr in /usr/lib/python2.7/dist-packages
Collecting M2Crypto
Requirement already satisfied (use --upgrade to upgrade): cherrypy in /usr/local/lib/python2.7/dist-packages
Requirement already satisfied (use --upgrade to upgrade): mako in /usr/lib/python2.7/dist-packages
Requirement already satisfied (use --upgrade to upgrade): typing in /usr/local/lib/python2.7/dist-packages (from M2Crypto)
Requirement already satisfied (use --upgrade to upgrade): six in /usr/lib/python2.7/dist-packages (from cherrypy)
Installing collected packages: M2Crypto
Successfully installed M2Crypto-0.25.1
root@kali:~# 

So after reinstalling it I,m getting this error:
\root@kali:/opt/pentest/RECON/spiderfoot-2.7.0# ./sf.py
Traceback (most recent call last):
  File "./sf.py", line 31, in <module>
    __import__(mod)
  File "/opt/pentest/RECON/spiderfoot-2.7.0/ext/bs4/__init__.py", line 30, in <module>
    from .builder import builder_registry, ParserRejectedMarkup
  File "/opt/pentest/RECON/spiderfoot-2.7.0/ext/bs4/builder/__init__.py", line 314, in <module>
    from . import _html5lib
  File "/opt/pentest/RECON/spiderfoot-2.7.0/ext/bs4/builder/_html5lib.py", line 70, in <module>
    class TreeBuilderForHtml5lib(html5lib.treebuilders._base.TreeBuilder):
AttributeError: 'module' object has no attribute '_base'
root@kali:/opt/pentest/RECON/spiderfoot-2.7.0# ./sf.py
Traceback (most recent call last):
  File "./sf.py", line 31, in <module>
    __import__(mod)
  File "/opt/pentest/RECON/spiderfoot-2.7.0/ext/bs4/__init__.py", line 30, in <module>
    from .builder import builder_registry, ParserRejectedMarkup
  File "/opt/pentest/RECON/spiderfoot-2.7.0/ext/bs4/builder/__init__.py", line 314, in <module>
    from . import _html5lib
  File "/opt/pentest/RECON/spiderfoot-2.7.0/ext/bs4/builder/_html5lib.py", line 70, in <module>
    class TreeBuilderForHtml5lib(html5lib.treebuilders._base.TreeBuilder):
AttributeError: 'module' object has no attribute '_base'
root@kali:/opt/pentest/RECON/spiderfoot-2.7.0# ./sf.py

**Comment by jteslaxxx** [comment]
Tried to patch like in issue #26 but seems no help!
