### ISSUE TITLE
Spiderfoot 500 ISE message after adding SSL and authentication file

### ISSUE THREAD

**Issue by mars01** [smicallef/spiderfoot#121]
Hi,

My SpiderFoot gives the following web browser error after I added SSL and a user authentication file:

```
**500 Internal Server Error**

The server encountered an unexpected condition which prevented it from fulfilling the request.

Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/usr/lib64/python2.7/site-packages/cherrypy/lib/encoding.py", line 220, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/cherrypy/_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/home/user/spiderfoot/sfwebui.py", line 375, in index
    templ = Template(filename='dyn/scanlist.tmpl', lookup=self.lookup)
  File "/usr/lib/python2.7/site-packages/mako/template.py", line 338, in __init__
    module = self._compile_from_file(path, filename)
  File "/usr/lib/python2.7/site-packages/mako/template.py", line 412, in _compile_from_file
    data = util.read_file(filename)
  File "/usr/lib/python2.7/site-packages/mako/util.py", line 365, in read_file
    fp = open(path, mode)
IOError: [Errno 2] No such file or directory: 'dyn/scanlist.tmpl'
Powered by CherryPy 8.9.1
```

I checked the auth file permissions, nothing different than all the other files in the spiderfoot directory. Ideas?

**Comment by smicallef** [comment]
How did you start SpiderFoot? It should have been from within the SpiderFoot directory itself, as ./sf.py.

**Comment by mars01** [comment]
Hi,

I ran it as "/usr/bin/python /home/<user>/spiderfoot/sf.py 0.0.0.0:5000".

**Comment by smicallef** [comment]
try instead:

cd /home/<user>/spiderfoot ; ./sf.py 0.0.0.0:5000
