### ISSUE TITLE
sf.py refuses to run

### ISSUE THREAD

**Issue by AppleDash48** [smicallef/spiderfoot#122]
I'm using the most recent version to-date from your website and all dependencies are installed according to the documentation.

I'm running as root, and I type in ./sf.py (It also occurs while trying "python ./sf.py" or "python sf.py")
Here is the output to the above command:

Traceback (most recent call last):
  File "./sf.py", line 31, in <module>
    __import__(mod)
  File "/root/Pentesting/spiderfoot-2.8.0/ext/bs4/__init__.py", line 30, in <module>
    from .builder import builder_registry, ParserRejectedMarkup
  File "/root/Pentesting/spiderfoot-2.8.0/ext/bs4/builder/__init__.py", line 314, in <module>
    from . import _html5lib
  File "/root/Pentesting/spiderfoot-2.8.0/ext/bs4/builder/_html5lib.py", line 70, in <module>
    class TreeBuilderForHtml5lib(html5lib.treebuilders._base.TreeBuilder):
AttributeError: 'module' object has no attribute '_base'

**Comment by smicallef** [comment]
Looks like the same issue as #115. Seems to be fixed by:

pip install --upgrade html5lib==1.0b8
