### ISSUE TITLE
Error when building the container

### ISSUE THREAD

**Issue by AC-WhiteGlint** [smicallef/spiderfoot#1227]
Hi,

I am using the master branch of Spiderfoot.

When building the container I receive this error 

```
Downloading scipy-1.7.0.tar.gz (36.1 MB)
  Installing build dependencies: started
  Installing build dependencies: still running...
  Installing build dependencies: finished with status 'error'
  ERROR: Command errored out with exit status 2:
   command: /opt/venv/bin/python3 /tmp/pip-standalone-pip-visj44xh/__env_pip__.zip/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-debe7pzd/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'wheel<0.37.0' 'setuptools<58.0.0' 'Cython>=0.29.18,<3.0' 'pybind11>=2.4.3,<2.7.0' pythran==0.9.11 'numpy==1.19.2; python_version=='"'"'3.7'"'"' and platform_machine=='"'"'aarch64'"'"'' 'numpy==1.19.2; python_version=='"'"'3.8'"'"' and platform_machine=='"'"'aarch64'"'"'' 'numpy==1.16.5; python_version=='"'"'3.7'"'"' and platform_machine!='"'"'aarch64'"'"' and platform_python_implementation != '"'"'PyPy'"'"'' 'numpy==1.17.3; python_version=='"'"'3.8'"'"' and platform_machine!='"'"'aarch64'"'"' and platform_python_implementation != '"'"'PyPy'"'"'' 'numpy==1.19.3; python_version=='"'"'3.9'"'"' and platform_python_implementation != '"'"'PyPy'"'"'' 'numpy==1.20.0; python_version=='"'"'3.7'"'"' and platform_python_implementation=='"'"'PyPy'"'"'' 'numpy; python_version=='"'"'3.8'"'"' and platform_python_implementation=='"'"'PyPy'"'"'' 'numpy; python_version=='"'"'3.9'"'"' and platform_python_implementation=='"'"'PyPy'"'"''
       cwd: None
  Complete output (93 lines):
  Ignoring numpy: markers 'python_version == "3.7" and platform_machine == "aarch64"' don't match your environment
  Ignoring numpy: markers 'python_version == "3.8" and platform_machine == "aarch64"' don't match your environment
  Ignoring numpy: markers 'python_version == "3.7" and platform_machine != "aarch64" and platform_python_implementation != "PyPy"' don't match your environment
  Ignoring numpy: markers 'python_version == "3.9" and platform_python_implementation != "PyPy"' don't match your environment
  Ignoring numpy: markers 'python_version == "3.7" and platform_python_implementation == "PyPy"' don't match your environment
  Ignoring numpy: markers 'python_version == "3.8" and platform_python_implementation == "PyPy"' don't match your environment
  Ignoring numpy: markers 'python_version == "3.9" and platform_python_implementation == "PyPy"' don't match your environment
  Collecting wheel<0.37.0
    Using cached wheel-0.36.2-py2.py3-none-any.whl (35 kB)
  Collecting setuptools<58.0.0
    Using cached setuptools-57.1.0-py3-none-any.whl (818 kB)
  Collecting Cython<3.0,>=0.29.18
    Using cached Cython-0.29.23-py2.py3-none-any.whl (978 kB)
  Collecting pybind11<2.7.0,>=2.4.3
    Downloading pybind11-2.6.2-py2.py3-none-any.whl (191 kB)
  Collecting pythran==0.9.11
    Downloading pythran-0.9.11-py3-none-any.whl (4.2 MB)
  Collecting numpy==1.17.3
    Downloading numpy-1.17.3.zip (6.4 MB)
  Collecting gast~=0.4.0
    Downloading gast-0.4.0-py3-none-any.whl (9.8 kB)
  Collecting beniget~=0.3.0
    Downloading beniget-0.3.0-py3-none-any.whl (9.3 kB)
  Collecting ply>=3.4
    Downloading ply-3.11-py2.py3-none-any.whl (49 kB)
  Collecting networkx>=2
    Using cached networkx-2.6.1-py3-none-any.whl (1.9 MB)
  Collecting decorator
    Downloading decorator-5.0.9-py3-none-any.whl (8.9 kB)
  Collecting six
    Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
  Collecting pandas>=1.1
    Using cached pandas-1.3.0.tar.gz (4.7 MB)
    Installing build dependencies: started
    Installing build dependencies: finished with status 'done'
    Getting requirements to build wheel: started
    Getting requirements to build wheel: still running...
    Getting requirements to build wheel: finished with status 'done'
      Preparing wheel metadata: started
      Preparing wheel metadata: finished with status 'done'
  Collecting scipy!=1.6.1,>=1.5
    Using cached scipy-1.7.0.tar.gz (36.1 MB)
  ERROR: Exception:
  Traceback (most recent call last):
    File "/tmp/pip-standalone-pip-visj44xh/__env_pip__.zip/pip/_internal/cli/base_command.py", line 180, in _main
      status = self.run(options, args)
    File "/tmp/pip-standalone-pip-visj44xh/__env_pip__.zip/pip/_internal/cli/req_command.py", line 205, in wrapper
      return func(self, options, args)
    File "/tmp/pip-standalone-pip-visj44xh/__env_pip__.zip/pip/_internal/commands/install.py", line 318, in run
      requirement_set = resolver.resolve(
    File "/tmp/pip-standalone-pip-visj44xh/__env_pip__.zip/pip/_internal/resolution/resolvelib/resolver.py", line 127, in resolve
      result = self._result = resolver.resolve(
    File "/tmp/pip-standalone-pip-visj44xh/__env_pip__.zip/pip/_vendor/resolvelib/resolvers.py", line 473, in resolve
      state = resolution.resolve(requirements, max_rounds=max_rounds)
    File "/tmp/pip-standalone-pip-visj44xh/__env_pip__.zip/pip/_vendor/resolvelib/resolvers.py", line 367, in resolve
      failure_causes = self._attempt_to_pin_criterion(name)
    File "/tmp/pip-standalone-pip-visj44xh/__env_pip__.zip/pip/_vendor/resolvelib/resolvers.py", line 213, in _attempt_to_pin_criterion
      criteria = self._get_criteria_to_update(candidate)
    File "/tmp/pip-standalone-pip-visj44xh/__env_pip__.zip/pip/_vendor/resolvelib/resolvers.py", line 203, in _get_criteria_to_update
      name, crit = self._merge_into_criterion(r, parent=candidate)
    File "/tmp/pip-standalone-pip-visj44xh/__env_pip__.zip/pip/_vendor/resolvelib/resolvers.py", line 172, in _merge_into_criterion
      if not criterion.candidates:
    File "/tmp/pip-standalone-pip-visj44xh/__env_pip__.zip/pip/_vendor/resolvelib/structs.py", line 139, in __bool__
      return bool(self._sequence)
    File "/tmp/pip-standalone-pip-visj44xh/__env_pip__.zip/pip/_internal/resolution/resolvelib/found_candidates.py", line 143, in __bool__
      return any(self)
    File "/tmp/pip-standalone-pip-visj44xh/__env_pip__.zip/pip/_internal/resolution/resolvelib/found_candidates.py", line 129, in <genexpr>
      return (c for c in iterator if id(c) not in self._incompatible_ids)
    File "/tmp/pip-standalone-pip-visj44xh/__env_pip__.zip/pip/_internal/resolution/resolvelib/found_candidates.py", line 33, in _iter_built
      candidate = func()
    File "/tmp/pip-standalone-pip-visj44xh/__env_pip__.zip/pip/_internal/resolution/resolvelib/factory.py", line 200, in _make_candidate_from_link
      self._link_candidate_cache[link] = LinkCandidate(
    File "/tmp/pip-standalone-pip-visj44xh/__env_pip__.zip/pip/_internal/resolution/resolvelib/candidates.py", line 306, in __init__
      super().__init__(
    File "/tmp/pip-standalone-pip-visj44xh/__env_pip__.zip/pip/_internal/resolution/resolvelib/candidates.py", line 151, in __init__
      self.dist = self._prepare()
    File "/tmp/pip-standalone-pip-visj44xh/__env_pip__.zip/pip/_internal/resolution/resolvelib/candidates.py", line 234, in _prepare
      dist = self._prepare_distribution()
    File "/tmp/pip-standalone-pip-visj44xh/__env_pip__.zip/pip/_internal/resolution/resolvelib/candidates.py", line 317, in _prepare_distribution
      return self._factory.preparer.prepare_linked_requirement(
    File "/tmp/pip-standalone-pip-visj44xh/__env_pip__.zip/pip/_internal/operations/prepare.py", line 508, in prepare_linked_requirement
      return self._prepare_linked_requirement(req, parallel_builds)
    File "/tmp/pip-standalone-pip-visj44xh/__env_pip__.zip/pip/_internal/operations/prepare.py", line 570, in _prepare_linked_requirement
      dist = _get_prepared_distribution(
    File "/tmp/pip-standalone-pip-visj44xh/__env_pip__.zip/pip/_internal/operations/prepare.py", line 59, in _get_prepared_distribution
      with req_tracker.track(req):
    File "/usr/lib/python3.8/contextlib.py", line 113, in __enter__
      return next(self.gen)
    File "/tmp/pip-standalone-pip-visj44xh/__env_pip__.zip/pip/_internal/req/req_tracker.py", line 138, in track
      self.add(req)
    File "/tmp/pip-standalone-pip-visj44xh/__env_pip__.zip/pip/_internal/req/req_tracker.py", line 104, in add
      raise LookupError(message)
  LookupError: https://files.pythonhosted.org/packages/bb/bb/944f559d554df6c9adf037aa9fc982a9706ee0e96c0d5beac701cb158900/scipy-1.7.0.tar.gz#sha256=998c5e6ea649489302de2c0bc026ed34284f531df89d2bdc8df3a0d44d165739 (from https://pypi.org/simple/scipy/) (requires-python:>=3.7,<3.10) is already being built: scipy!=1.6.1,>=1.5 from https://files.pythonhosted.org/packages/bb/bb/944f559d554df6c9adf037aa9fc982a9706ee0e96c0d5beac701cb158900/scipy-1.7.0.tar.gz#sha256=998c5e6ea649489302de2c0bc026ed34284f531df89d2bdc8df3a0d44d165739 (from networkx>=2.5->-r requirements.txt (line 22))
  ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/bb/bb/944f559d554df6c9adf037aa9fc982a9706ee0e96c0d5beac701cb158900/scipy-1.7.0.tar.gz#sha256=998c5e6ea649489302de2c0bc026ed34284f531df89d2bdc8df3a0d44d165739 (from https://pypi.org/simple/scipy/) (requires-python:>=3.7,<3.10). Command errored out with exit status 2: /opt/venv/bin/python3 /tmp/pip-standalone-pip-visj44xh/__env_pip__.zip/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-debe7pzd/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'wheel<0.37.0' 'setuptools<58.0.0' 'Cython>=0.29.18,<3.0' 'pybind11>=2.4.3,<2.7.0' pythran==0.9.11 'numpy==1.19.2; python_version=='"'"'3.7'"'"' and platform_machine=='"'"'aarch64'"'"'' 'numpy==1.19.2; python_version=='"'"'3.8'"'"' and platform_machine=='"'"'aarch64'"'"'' 'numpy==1.16.5; python_version=='"'"'3.7'"'"' and platform_machine!='"'"'aarch64'"'"' and platform_python_implementation != '"'"'PyPy'"'"'' 'numpy==1.17.3; python_version=='"'"'3.8'"'"' and platform_machine!='"'"'aarch64'"'"' and platform_python_implementation != '"'"'PyPy'"'"'' 'numpy==1.19.3; python_version=='"'"'3.9'"'"' and platform_python_implementation != '"'"'PyPy'"'"'' 'numpy==1.20.0; python_version=='"'"'3.7'"'"' and platform_python_implementation=='"'"'PyPy'"'"'' 'numpy; python_version=='"'"'3.8'"'"' and platform_python_implementation=='"'"'PyPy'"'"'' 'numpy; python_version=='"'"'3.9'"'"' and platform_python_implementation=='"'"'PyPy'"'"'' Check the logs for full command output.

```
The build is still successfull despite this error and Spiderffot works.

it is impossible to install any version of scipy (it tries different version before moving on)

It cannot find BLAS/LAPACK libraries.

Is Scipy necessary for Spiderfoot will any feature break without it?

Any idea how to solve this?

**Comment by craig** [comment]
Tested just now: the build completes without any issues.
