### ISSUE TITLE
Threading intermittent issue

### ISSUE THREAD

**Issue by bcoles** [smicallef/spiderfoot#1346]
Something is horribly wrong with the threading.

These errors show up intermittantly during the tests (40 times).

<details>

```
[2021-09-05 07:21:17] root@kali:~/Desktop/spiderfoot# ./test/run 
==================================================================================== test session starts =====================================================================================
platform linux -- Python 3.9.2, pytest-6.2.5, py-1.10.0, pluggy-0.13.0
rootdir: /root/Desktop/spiderfoot
plugins: cov-2.12.1, mock-3.6.1, flake8-1.0.6, xdist-2.2.1, forked-1.3.0
gw0 [2105] / gw1 [2105]
...................................................................................................................................................................................... [  8%]
....................................................................s.............s.......ss.............................................s......s.............................s....... [ 17%]
...................................ss.s...........................................................ss...................................................ss......ssss...s..sss.......s.. [ 25%]
......s..ssss...sss...s.....ss....s.....s......s..ss....s.....ss....s.....ss....ss....s.....ss....s.....ss....s......s.....s.....s.....s.....s.....s......s.....s.....ss....ss....s... [ 34%]
..ss....s.....s.....s.....s.....s.....ss....s.....ss....s......ss....s.....s......ss....ss....s......s............s......s......s.....ss....ss....ss....ss....ss....ss....ss....s..... [ 43%]
ss....s.....ss....s.....ss....ss.....s.....s.....s..........s.....s.....ss....s.....s.....ss....ss....s.....s........s......s.....s.....ss....ss....s.....ss....s.....s.....ss....ss.. [ 51%]
..s.....ss....s.....s.....ss....s.....s.....ss....s.....ss....ss....s......s.....s.....sss....s.....s.....s.....s......s.....s.....s.....s.....ss....s.....s.....s.....s.....s.....ss. [ 60%]
...s.....ss....ss....ss....s.....ss....ss....s.....s.....ss....ss....s.....s.....s........s.....s.....s.....s.....ss....s.....ss....ss....ss....s......ss....ss....s.....s.....s.....s [ 69%]
s....ss....s.......s.....s.....ss....s.....ss....s......s.....ss....s.....s.....ss....ss....ss....ss....s.....s.....s.....ss....ss....s.....s.....s.....s.....s.....s.....s.....s..... [ 77%]
ss....s.....s.....s.....s.....ss.........s.....ss....ss....s....s.....ss....ss....ss....s.....s.....s.....s.....s......s...s...s.s.....s.......sss.......s.......sss.....ss......s....s [ 86%]
.....s.s......sss.......s.....s.....s.........s...s......s......s...s....ss....s.....s......s.....ss..........s.........................................s...s......................... [ 95%]
s.....................................................................2021-09-05 07:24:06,078 [ERROR] Exception (ValueError) in module module_name_not_set!.Traceback (most recent call last):
  File "/root/Desktop/spiderfoot/spiderfoot/plugin.py", line 364, in threadWorker
    self.setDbh(SpiderFootDb(self.opts))
  File "/root/Desktop/spiderfoot/spiderfoot/db.py", line 270, in __init__
    raise ValueError("opts is empty")
ValueError: opts is empty

2021-09-05 07:24:06,078 [ERROR] Exception (ValueError) in module module_name_not_set!.Traceback (most recent call last):
  File "/root/Desktop/spiderfoot/spiderfoot/plugin.py", line 364, in threadWorker
    self.setDbh(SpiderFootDb(self.opts))
  File "/root/Desktop/spiderfoot/spiderfoot/db.py", line 270, in __init__
    raise ValueError("opts is empty")
ValueError: opts is empty

2021-09-05 07:24:06,078 [ERROR] Exception (ValueError) in module module_name_not_set!.Traceback (most recent call last):
  File "/root/Desktop/spiderfoot/spiderfoot/plugin.py", line 364, in threadWorker
    self.setDbh(SpiderFootDb(self.opts))
  File "/root/Desktop/spiderfoot/spiderfoot/db.py", line 270, in __init__
    raise ValueError("opts is empty")
ValueError: opts is empty

2021-09-05 07:24:06,078 [ERROR] Exception (ValueError) in module module_name_not_set!.Traceback (most recent call last):
  File "/root/Desktop/spiderfoot/spiderfoot/plugin.py", line 364, in threadWorker
    self.setDbh(SpiderFootDb(self.opts))
  File "/root/Desktop/spiderfoot/spiderfoot/db.py", line 270, in __init__
    raise ValueError("opts is empty")
ValueError: opts is empty

2021-09-05 07:24:06,078 [ERROR] Exception (ValueError) in module module_name_not_set!.Traceback (most recent call last):
  File "/root/Desktop/spiderfoot/spiderfoot/plugin.py", line 364, in threadWorker
    self.setDbh(SpiderFootDb(self.opts))
  File "/root/Desktop/spiderfoot/spiderfoot/db.py", line 270, in __init__
    raise ValueError("opts is empty")
ValueError: opts is empty

2021-09-05 07:24:06,078 [ERROR] Exception (ValueError) in module module_name_not_set!.Traceback (most recent call last):
  File "/root/Desktop/spiderfoot/spiderfoot/plugin.py", line 364, in threadWorker
    self.setDbh(SpiderFootDb(self.opts))
  File "/root/Desktop/spiderfoot/spiderfoot/db.py", line 270, in __init__
    raise ValueError("opts is empty")
ValueError: opts is empty

2021-09-05 07:24:06,078 [ERROR] Exception (ValueError) in module module_name_not_set!.Traceback (most recent call last):
  File "/root/Desktop/spiderfoot/spiderfoot/plugin.py", line 364, in threadWorker
    self.setDbh(SpiderFootDb(self.opts))
  File "/root/Desktop/spiderfoot/spiderfoot/db.py", line 270, in __init__
    raise ValueError("opts is empty")
ValueError: opts is empty

2021-09-05 07:24:06,078 [ERROR] Exception (ValueError) in module module_name_not_set!.Traceback (most recent call last):
  File "/root/Desktop/spiderfoot/spiderfoot/plugin.py", line 364, in threadWorker
    self.setDbh(SpiderFootDb(self.opts))
  File "/root/Desktop/spiderfoot/spiderfoot/db.py", line 270, in __init__
    raise ValueError("opts is empty")
ValueError: opts is empty

2021-09-05 07:24:06,078 [ERROR] Exception (ValueError) in module module_name_not_set!.Traceback (most recent call last):
  File "/root/Desktop/spiderfoot/spiderfoot/plugin.py", line 364, in threadWorker
    self.setDbh(SpiderFootDb(self.opts))
  File "/root/Desktop/spiderfoot/spiderfoot/db.py", line 270, in __init__
    raise ValueError("opts is empty")
ValueError: opts is empty

2021-09-05 07:24:06,078 [ERROR] Exception (ValueError) in module module_name_not_set!.Traceback (most recent call last):
  File "/root/Desktop/spiderfoot/spiderfoot/plugin.py", line 364, in threadWorker
    self.setDbh(SpiderFootDb(self.opts))
  File "/root/Desktop/spiderfoot/spiderfoot/db.py", line 270, in __init__
    raise ValueError("opts is empty")
ValueError: opts is empty

2021-09-05 07:24:06,078 [ERROR] Exception (ValueError) in module module_name_not_set!.Traceback (most recent call last):
  File "/root/Desktop/spiderfoot/spiderfoot/plugin.py", line 364, in threadWorker
    self.setDbh(SpiderFootDb(self.opts))
  File "/root/Desktop/spiderfoot/spiderfoot/db.py", line 270, in __init__
    raise ValueError("opts is empty")
ValueError: opts is empty

2021-09-05 07:24:06,078 [ERROR] Exception (ValueError) in module module_name_not_set!.Traceback (most recent call last):
  File "/root/Desktop/spiderfoot/spiderfoot/plugin.py", line 364, in threadWorker
    self.setDbh(SpiderFootDb(self.opts))
  File "/root/Desktop/spiderfoot/spiderfoot/db.py", line 270, in __init__
    raise ValueError("opts is empty")
ValueError: opts is empty

2021-09-05 07:24:06,078 [ERROR] Exception (ValueError) in module module_name_not_set!.Traceback (most recent call last):
  File "/root/Desktop/spiderfoot/spiderfoot/plugin.py", line 364, in threadWorker
    self.setDbh(SpiderFootDb(self.opts))
  File "/root/Desktop/spiderfoot/spiderfoot/db.py", line 270, in __init__
    raise ValueError("opts is empty")
ValueError: opts is empty

2021-09-05 07:24:06,078 [ERROR] Exception (ValueError) in module module_name_not_set!.Traceback (most recent call last):
  File "/root/Desktop/spiderfoot/spiderfoot/plugin.py", line 364, in threadWorker
    self.setDbh(SpiderFootDb(self.opts))
  File "/root/Desktop/spiderfoot/spiderfoot/db.py", line 270, in __init__
    raise ValueError("opts is empty")
ValueError: opts is empty

2021-09-05 07:24:06,078 [ERROR] Exception (ValueError) in module module_name_not_set!.Traceback (most recent call last):
  File "/root/Desktop/spiderfoot/spiderfoot/plugin.py", line 364, in threadWorker
    self.setDbh(SpiderFootDb(self.opts))
  File "/root/Desktop/spiderfoot/spiderfoot/db.py", line 270, in __init__
    raise ValueError("opts is empty")
ValueError: opts is empty

2021-09-05 07:24:06,078 [ERROR] Exception (ValueError) in module module_name_not_set!.Traceback (most recent call last):
  File "/root/Desktop/spiderfoot/spiderfoot/plugin.py", line 364, in threadWorker
    self.setDbh(SpiderFootDb(self.opts))
  File "/root/Desktop/spiderfoot/spiderfoot/db.py", line 270, in __init__
    raise ValueError("opts is empty")
ValueError: opts is empty

2021-09-05 07:24:06,078 [ERROR] Exception (ValueError) in module module_name_not_set!.Traceback (most recent call last):
  File "/root/Desktop/spiderfoot/spiderfoot/plugin.py", line 364, in threadWorker
    self.setDbh(SpiderFootDb(self.opts))
  File "/root/Desktop/spiderfoot/spiderfoot/db.py", line 270, in __init__
    raise ValueError("opts is empty")
ValueError: opts is empty

2021-09-05 07:24:06,078 [ERROR] Exception (ValueError) in module module_name_not_set!.Traceback (most recent call last):
  File "/root/Desktop/spiderfoot/spiderfoot/plugin.py", line 364, in threadWorker
    self.setDbh(SpiderFootDb(self.opts))
  File "/root/Desktop/spiderfoot/spiderfoot/db.py", line 270, in __init__
    raise ValueError("opts is empty")
ValueError: opts is empty

2021-09-05 07:24:06,078 [ERROR] Exception (ValueError) in module module_name_not_set!.Traceback (most recent call last):
  File "/root/Desktop/spiderfoot/spiderfoot/plugin.py", line 364, in threadWorker
    self.setDbh(SpiderFootDb(self.opts))
  File "/root/Desktop/spiderfoot/spiderfoot/db.py", line 270, in __init__
    raise ValueError("opts is empty")
ValueError: opts is empty

2021-09-05 07:24:06,078 [ERROR] Exception (ValueError) in module module_name_not_set!.Traceback (most recent call last):
  File "/root/Desktop/spiderfoot/spiderfoot/plugin.py", line 364, in threadWorker
    self.setDbh(SpiderFootDb(self.opts))
  File "/root/Desktop/spiderfoot/spiderfoot/db.py", line 270, in __init__
    raise ValueError("opts is empty")
ValueError: opts is empty

2021-09-05 07:24:06,078 [ERROR] Exception (ValueError) in module module_name_not_set!.Traceback (most recent call last):
  File "/root/Desktop/spiderfoot/spiderfoot/plugin.py", line 364, in threadWorker
    self.setDbh(SpiderFootDb(self.opts))
  File "/root/Desktop/spiderfoot/spiderfoot/db.py", line 270, in __init__
    raise ValueError("opts is empty")
ValueError: opts is empty

2021-09-05 07:24:06,078 [ERROR] Exception (ValueError) in module module_name_not_set!.Traceback (most recent call last):
  File "/root/Desktop/spiderfoot/spiderfoot/plugin.py", line 364, in threadWorker
    self.setDbh(SpiderFootDb(self.opts))
  File "/root/Desktop/spiderfoot/spiderfoot/db.py", line 270, in __init__
    raise ValueError("opts is empty")
ValueError: opts is empty

2021-09-05 07:24:06,078 [ERROR] Exception (ValueError) in module module_name_not_set!.Traceback (most recent call last):
  File "/root/Desktop/spiderfoot/spiderfoot/plugin.py", line 364, in threadWorker
    self.setDbh(SpiderFootDb(self.opts))
  File "/root/Desktop/spiderfoot/spiderfoot/db.py", line 270, in __init__
    raise ValueError("opts is empty")
ValueError: opts is empty

2021-09-05 07:24:06,078 [ERROR] Exception (ValueError) in module module_name_not_set!.Traceback (most recent call last):
  File "/root/Desktop/spiderfoot/spiderfoot/plugin.py", line 364, in threadWorker
    self.setDbh(SpiderFootDb(self.opts))
  File "/root/Desktop/spiderfoot/spiderfoot/db.py", line 270, in __init__
    raise ValueError("opts is empty")
ValueError: opts is empty

2021-09-05 07:24:06,078 [ERROR] Exception (ValueError) in module module_name_not_set!.Traceback (most recent call last):
  File "/root/Desktop/spiderfoot/spiderfoot/plugin.py", line 364, in threadWorker
    self.setDbh(SpiderFootDb(self.opts))
  File "/root/Desktop/spiderfoot/spiderfoot/db.py", line 270, in __init__
    raise ValueError("opts is empty")
ValueError: opts is empty

2021-09-05 07:24:06,078 [ERROR] Exception (ValueError) in module module_name_not_set!.Traceback (most recent call last):
  File "/root/Desktop/spiderfoot/spiderfoot/plugin.py", line 364, in threadWorker
    self.setDbh(SpiderFootDb(self.opts))
  File "/root/Desktop/spiderfoot/spiderfoot/db.py", line 270, in __init__
    raise ValueError("opts is empty")
ValueError: opts is empty

2021-09-05 07:24:06,078 [ERROR] Exception (ValueError) in module module_name_not_set!.Traceback (most recent call last):
  File "/root/Desktop/spiderfoot/spiderfoot/plugin.py", line 364, in threadWorker
    self.setDbh(SpiderFootDb(self.opts))
  File "/root/Desktop/spiderfoot/spiderfoot/db.py", line 270, in __init__
    raise ValueError("opts is empty")
ValueError: opts is empty

2021-09-05 07:24:06,078 [ERROR] Exception (ValueError) in module module_name_not_set!.Traceback (most recent call last):
  File "/root/Desktop/spiderfoot/spiderfoot/plugin.py", line 364, in threadWorker
    self.setDbh(SpiderFootDb(self.opts))
  File "/root/Desktop/spiderfoot/spiderfoot/db.py", line 270, in __init__
    raise ValueError("opts is empty")
ValueError: opts is empty

2021-09-05 07:24:06,078 [ERROR] Exception (ValueError) in module module_name_not_set!.Traceback (most recent call last):
  File "/root/Desktop/spiderfoot/spiderfoot/plugin.py", line 364, in threadWorker
    self.setDbh(SpiderFootDb(self.opts))
  File "/root/Desktop/spiderfoot/spiderfoot/db.py", line 270, in __init__
    raise ValueError("opts is empty")
ValueError: opts is empty

2021-09-05 07:24:06,078 [ERROR] Exception (ValueError) in module module_name_not_set!.Traceback (most recent call last):
  File "/root/Desktop/spiderfoot/spiderfoot/plugin.py", line 364, in threadWorker
    self.setDbh(SpiderFootDb(self.opts))
  File "/root/Desktop/spiderfoot/spiderfoot/db.py", line 270, in __init__
    raise ValueError("opts is empty")
ValueError: opts is empty

2021-09-05 07:24:06,078 [ERROR] Exception (ValueError) in module module_name_not_set!.Traceback (most recent call last):
  File "/root/Desktop/spiderfoot/spiderfoot/plugin.py", line 364, in threadWorker
    self.setDbh(SpiderFootDb(self.opts))
  File "/root/Desktop/spiderfoot/spiderfoot/db.py", line 270, in __init__
    raise ValueError("opts is empty")
ValueError: opts is empty

2021-09-05 07:24:06,078 [ERROR] Exception (ValueError) in module module_name_not_set!.Traceback (most recent call last):
  File "/root/Desktop/spiderfoot/spiderfoot/plugin.py", line 364, in threadWorker
    self.setDbh(SpiderFootDb(self.opts))
  File "/root/Desktop/spiderfoot/spiderfoot/db.py", line 270, in __init__
    raise ValueError("opts is empty")
ValueError: opts is empty

2021-09-05 07:24:06,078 [ERROR] Exception (ValueError) in module module_name_not_set!.Traceback (most recent call last):
  File "/root/Desktop/spiderfoot/spiderfoot/plugin.py", line 364, in threadWorker
    self.setDbh(SpiderFootDb(self.opts))
  File "/root/Desktop/spiderfoot/spiderfoot/db.py", line 270, in __init__
    raise ValueError("opts is empty")
ValueError: opts is empty

2021-09-05 07:24:06,078 [ERROR] Exception (ValueError) in module module_name_not_set!.Traceback (most recent call last):
  File "/root/Desktop/spiderfoot/spiderfoot/plugin.py", line 364, in threadWorker
    self.setDbh(SpiderFootDb(self.opts))
  File "/root/Desktop/spiderfoot/spiderfoot/db.py", line 270, in __init__
    raise ValueError("opts is empty")
ValueError: opts is empty

2021-09-05 07:24:06,078 [ERROR] Exception (ValueError) in module module_name_not_set!.Traceback (most recent call last):
  File "/root/Desktop/spiderfoot/spiderfoot/plugin.py", line 364, in threadWorker
    self.setDbh(SpiderFootDb(self.opts))
  File "/root/Desktop/spiderfoot/spiderfoot/db.py", line 270, in __init__
    raise ValueError("opts is empty")
ValueError: opts is empty

2021-09-05 07:24:06,078 [ERROR] Exception (ValueError) in module module_name_not_set!.Traceback (most recent call last):
  File "/root/Desktop/spiderfoot/spiderfoot/plugin.py", line 364, in threadWorker
    self.setDbh(SpiderFootDb(self.opts))
  File "/root/Desktop/spiderfoot/spiderfoot/db.py", line 270, in __init__
    raise ValueError("opts is empty")
ValueError: opts is empty

2021-09-05 07:24:06,078 [ERROR] Exception (ValueError) in module module_name_not_set!.Traceback (most recent call last):
  File "/root/Desktop/spiderfoot/spiderfoot/plugin.py", line 364, in threadWorker
    self.setDbh(SpiderFootDb(self.opts))
  File "/root/Desktop/spiderfoot/spiderfoot/db.py", line 270, in __init__
    raise ValueError("opts is empty")
ValueError: opts is empty

2021-09-05 07:24:06,078 [ERROR] Exception (ValueError) in module module_name_not_set!.Traceback (most recent call last):
  File "/root/Desktop/spiderfoot/spiderfoot/plugin.py", line 364, in threadWorker
    self.setDbh(SpiderFootDb(self.opts))
  File "/root/Desktop/spiderfoot/spiderfoot/db.py", line 270, in __init__
    raise ValueError("opts is empty")
ValueError: opts is empty

2021-09-05 07:24:06,078 [ERROR] Exception (ValueError) in module module_name_not_set!.Traceback (most recent call last):
  File "/root/Desktop/spiderfoot/spiderfoot/plugin.py", line 364, in threadWorker
    self.setDbh(SpiderFootDb(self.opts))
  File "/root/Desktop/spiderfoot/spiderfoot/db.py", line 270, in __init__
    raise ValueError("opts is empty")
ValueError: opts is empty

................................                                                                                 [100%]
====================================================================================== warnings summary ======================================================================================
../../../usr/lib/python3/dist-packages/future/standard_library/__init__.py:65
../../../usr/lib/python3/dist-packages/future/standard_library/__init__.py:65
  /usr/lib/python3/dist-packages/future/standard_library/__init__.py:65: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
    import imp

-- Docs: https://docs.pytest.org/en/stable/warnings.html

----------- coverage: platform linux, python 3.9.2-final-0 -----------
Coverage HTML written to dir htmlcov

==================================================================================== slowest 5 durations =====================================================================================
37.18s call     sflib.py::FLAKE8
18.80s call     sfwebui.py::FLAKE8
17.08s call     spiderfoot/db.py::FLAKE8
7.58s call     sfscan.py::FLAKE8
7.45s call     test/unit/modules/test_sfp_adblock.py::TestModuleadblock::test_handleEvent_event_data_provider_javascript_url_matching_ad_filter_should_return_event
================================================================= 1768 passed, 337 skipped, 2 warnings in 160.98s (0:02:40) ==================================================================

real	2m41.684s
user	4m43.510s
sys	0m15.150s
```

</details>

Log records are also duplicated (40 times):

<details>

```
2021-09-05 08:43:15,655 [INFO] modules.sfp_portscan_tcp : Spawning thread to check port: 21 on example data
2021-09-05 08:43:15,655 [INFO] modules.sfp_portscan_tcp : Spawning thread to check port: 21 on example data
2021-09-05 08:43:15,655 [INFO] modules.sfp_portscan_tcp : Spawning thread to check port: 21 on example data
2021-09-05 08:43:15,655 [INFO] modules.sfp_portscan_tcp : Spawning thread to check port: 21 on example data
2021-09-05 08:43:15,655 [INFO] modules.sfp_portscan_tcp : Spawning thread to check port: 21 on example data
2021-09-05 08:43:15,655 [INFO] modules.sfp_portscan_tcp : Spawning thread to check port: 21 on example data
2021-09-05 08:43:15,655 [INFO] modules.sfp_portscan_tcp : Spawning thread to check port: 21 on example data
2021-09-05 08:43:15,655 [INFO] modules.sfp_portscan_tcp : Spawning thread to check port: 21 on example data
2021-09-05 08:43:15,655 [INFO] modules.sfp_portscan_tcp : Spawning thread to check port: 21 on example data
2021-09-05 08:43:15,655 [INFO] modules.sfp_portscan_tcp : Spawning thread to check port: 21 on example data
2021-09-05 08:43:15,655 [INFO] modules.sfp_portscan_tcp : Spawning thread to check port: 21 on example data
2021-09-05 08:43:15,655 [INFO] modules.sfp_portscan_tcp : Spawning thread to check port: 21 on example data
2021-09-05 08:43:15,655 [INFO] modules.sfp_portscan_tcp : Spawning thread to check port: 21 on example data
2021-09-05 08:43:15,655 [INFO] modules.sfp_portscan_tcp : Spawning thread to check port: 21 on example data
2021-09-05 08:43:15,655 [INFO] modules.sfp_portscan_tcp : Spawning thread to check port: 21 on example data
2021-09-05 08:43:15,655 [INFO] modules.sfp_portscan_tcp : Spawning thread to check port: 21 on example data
2021-09-05 08:43:15,655 [INFO] modules.sfp_portscan_tcp : Spawning thread to check port: 21 on example data
2021-09-05 08:43:15,655 [INFO] modules.sfp_portscan_tcp : Spawning thread to check port: 21 on example data
2021-09-05 08:43:15,655 [INFO] modules.sfp_portscan_tcp : Spawning thread to check port: 21 on example data
2021-09-05 08:43:15,655 [INFO] modules.sfp_portscan_tcp : Spawning thread to check port: 21 on example data
2021-09-05 08:43:15,655 [INFO] modules.sfp_portscan_tcp : Spawning thread to check port: 21 on example data
2021-09-05 08:43:15,655 [INFO] modules.sfp_portscan_tcp : Spawning thread to check port: 21 on example data
2021-09-05 08:43:15,655 [INFO] modules.sfp_portscan_tcp : Spawning thread to check port: 21 on example data
2021-09-05 08:43:15,655 [INFO] modules.sfp_portscan_tcp : Spawning thread to check port: 21 on example data
2021-09-05 08:43:15,655 [INFO] modules.sfp_portscan_tcp : Spawning thread to check port: 21 on example data
2021-09-05 08:43:15,655 [INFO] modules.sfp_portscan_tcp : Spawning thread to check port: 21 on example data
2021-09-05 08:43:15,655 [INFO] modules.sfp_portscan_tcp : Spawning thread to check port: 21 on example data
2021-09-05 08:43:15,655 [INFO] modules.sfp_portscan_tcp : Spawning thread to check port: 21 on example data
2021-09-05 08:43:15,655 [INFO] modules.sfp_portscan_tcp : Spawning thread to check port: 21 on example data
2021-09-05 08:43:15,655 [INFO] modules.sfp_portscan_tcp : Spawning thread to check port: 21 on example data
2021-09-05 08:43:15,655 [INFO] modules.sfp_portscan_tcp : Spawning thread to check port: 21 on example data
2021-09-05 08:43:15,655 [INFO] modules.sfp_portscan_tcp : Spawning thread to check port: 21 on example data
2021-09-05 08:43:15,655 [INFO] modules.sfp_portscan_tcp : Spawning thread to check port: 21 on example data
2021-09-05 08:43:15,655 [INFO] modules.sfp_portscan_tcp : Spawning thread to check port: 21 on example data
2021-09-05 08:43:15,655 [INFO] modules.sfp_portscan_tcp : Spawning thread to check port: 21 on example data
2021-09-05 08:43:15,655 [INFO] modules.sfp_portscan_tcp : Spawning thread to check port: 21 on example data
2021-09-05 08:43:15,655 [INFO] modules.sfp_portscan_tcp : Spawning thread to check port: 21 on example data
```

</details>

**Comment by bcoles** [comment]
Probably fixed in #1347
