### ISSUE TITLE
Error Message When Attempt Simple IP Scan

### ISSUE THREAD

**Issue by leoclark13** [smicallef/spiderfoot#139]
When attempting a simple IP scan I get the following error messages:

1 | 2 | 3 | 4
-- | -- | -- | --
2017-07-10 00:16:56 | SpiderFoot | STATUS | Scan [2972A692] failed: Internal Error Encountered: Unable to open option URL, https://publicsuffix.org/list/effective_tld_names.dat: <urlopen error [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:661)>
2017-07-10 00:16:56 | SpiderFoot | ERROR | Unhandled exception (BaseException) encountered during scan. Please report this as a bug: ['Traceback (most recent call last):\n', '  File "/Users/rlmcguire/Downloads/spiderfoot-2.10/sfscan.py", line 184, in startScan\n    self.ts.config[\'_internettlds\'])\n', '  File "/Users/rlmcguire/Downloads/spiderfoot-2.10/sflib.py", line 116, in optValueToData\n    self.error("Unable to open option URL, " + val + ": " + str(e))\n', '  File "/Users/rlmcguire/Downloads/spiderfoot-2.10/sflib.py", line 298, in error\n    raise BaseException("Internal Error Encountered: " + error)\n', 'BaseException: Internal Error Encountered: Unable to open option URL, https://publicsuffix.org/list/effective_tld_names.dat: <urlopen error [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:661)>\n']
2017-07-10 00:16:56 | SpiderFoot | ERROR | Unable to open option URL, https://publicsuffix.org/list/effective_tld_names.dat: <urlopen error [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:661)>
2017-07-10 00:16:55 | sfscan | INFO | Downloading configuration data from: https://publicsuffix.org/list/effective_tld_names.dat
2017-07-10 00:16:55 | SpiderFoot | STATUS | Scan [2972A692] initiated.

Thank you,
Leo

**Comment by bcoles** [comment]
Looks like a connection issue. Is `publicsuffix.org` resolvable and routable?
