### ISSUE TITLE
IOError: [Errno 2] No such file or directory: 'dyn/scanlist.tmpl'

### ISSUE THREAD

**Issue by anniesbbs** [smicallef/spiderfoot#144]
Attempting to access the webpage results in a 500 Internal Server Error where the error is that sf.py cannot find dyn/scanlist.tmpl. Upon inspecting the Spiderfoot folder, I find that dyn/scanlist.tmpl does exist. 

Maybe I messed up permissions? seems fine to me

500 Internal Server Error

The server encountered an unexpected condition which prevented it from fulfilling the request.

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/lib/encoding.py", line 221, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/home/$USER/spiderfoot-2.11.0/sfwebui.py", line 378, in index
    templ = Template(filename='dyn/scanlist.tmpl', lookup=self.lookup)
  File "/usr/local/lib/python2.7/dist-packages/mako/template.py", line 338, in __init__
    module = self._compile_from_file(path, filename)
  File "/usr/local/lib/python2.7/dist-packages/mako/template.py", line 412, in _compile_from_file
    data = util.read_file(filename)
  File "/usr/local/lib/python2.7/dist-packages/mako/util.py", line 365, in read_file
    fp = open(path, mode)
IOError: [Errno 2] No such file or directory: 'dyn/scanlist.tmpl'
Powered by CherryPy 11.0.0

USER@HOSTNAME:~ » ls -l spiderfoot/dyn 
total 92
-rw-r--r-- 1 USER GROUP   258 Aug 16 13:08 error.tmpl
-rw-r--r-- 1 USER GROUP    31 Aug 16 13:08 FOOTER.tmpl
-rw-r--r-- 1 USER GROUP  4522 Aug 16 13:08 HEADER.tmpl
-rw-r--r-- 1 USER GROUP  7049 Aug 16 13:08 newscan.tmpl
-rw-r--r-- 1 USER GROUP  5823 Aug 16 13:08 opts.tmpl
-rw-r--r-- 1 USER GROUP   581 Aug 16 13:08 scandelete.tmpl
-rw-r--r-- 1 USER GROUP 39314 Aug 16 13:08 scaninfo.tmpl
-rw-r--r-- 1 USER GROUP 13181 Aug 16 13:08 scanlist.tmpl

**Comment by smicallef** [comment]
This is because SpiderFoot needs to run out of its own directory. You need to be inside your SpiderFoot folder when running it.
