### ISSUE TITLE
Error When Trying To Reputation Scan IP

### ISSUE THREAD

**Issue by Yuvalshitrit** [smicallef/spiderfoot#1599]
Traceback (most recent call last):
  File "/Users/yuvalshitrit/Documents/DEV/spiderfoot/spiderfoot-3.4/spiderfoot/db.py", line 311, in __init__
  File "/Users/yuvalshitrit/Documents/DEV/spiderfoot/spiderfoot-3.4/spiderfoot/db.py", line 361, in create
OSError: SQL error encountered when setting up database: unable to open database file

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yuvalshitrit/Documents/DEV/spiderfoot/spiderfoot-3.4/spiderfoot/plugin.py", line 348, in threadWorker
  File "/Users/yuvalshitrit/Documents/DEV/spiderfoot/spiderfoot-3.4/spiderfoot/db.py", line 314, in __init__
OSError: Tried to set up the SpiderFoot database schema, but failed: SQL error encountered when setting up database: unable to open database file

2021-11-10 17:02:00,041 [ERROR] Unhandled exception (OSError) encountered during scan.Please report this as a bug: ['Traceback (most recent call last):\n', '  File "/Users/yuvalshitrit/Documents/DEV/spiderfoot/spiderfoot-3.4/sfscan.py", line 384, in __startScan\n    self.waitForThreads()\n', '  File "/Users/yuvalshitrit/Documents/DEV/spiderfoot/spiderfoot-3.4/sfscan.py", line 422, in waitForThreads\n    self.__sf.debug(f"waitForThreads() got event, {sfEvent.eventType}, from eventQueue.")\n', '  File "/Users/yuvalshitrit/Documents/DEV/spiderfoot/spiderfoot-3.4/sflib.py", line 296, in debug\n    frm = inspect.stack()[1]\n', '  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/inspect.py", line 1552, in stack\n', '  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/inspect.py", line 1529, in getouterframes\n', '  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/inspect.py", line 1499, in getframeinfo\n', '  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/inspect.py", line 709, in getsourcefile\n', '  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/inspect.py", line 738, in getmodule\n', '  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/inspect.py", line 722, in getabsfile\n', '  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/posixpath.py", line 379, in abspath\n', 'OSError: [Errno 24] Too many open files\n']
2021-11-10 17:02:00,059 [INFO] Scan [7650C9AB] failed: [Errno 24] Too many open files

**Comment by smicallef** [comment]
A number of fixes were implemented in 3.5 - could you verify that this is still happening?
