### ISSUE TITLE
 failed: 'ascii' codec can't decode byte 0xff in 

### ISSUE THREAD

**Issue by mgtremaine** [smicallef/spiderfoot#161]
New user here so it could be me but I have not been able to complete a scan yet. The last one crash with this.

Error from Logs:

2017-11-11 11:05:41 | SpiderFoot | STATUS | Scan [E38A2151] failed: 'ascii' codec can't decode byte 0xff in position 33: ordinal not in range(128)

2017-11-11 11:05:41 | SpiderFoot | ERROR | Unhandled exception (UnicodeDecodeError) encountered during scan. Please report this as a bug: ['Traceback (most recent call last):\n', '  File "/home/system/scanners/spiderfoot/sfscan.py", line 265, in startScan\n    psMod.notifyListeners(firstEvent)\n', '  File "/home/system/scanners/spiderfoot/sflib.py", line 1523, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "/home/system/scanners/spiderfoot/modules/sfp_bingsearch.py", line 93, in handleEvent\n    self.notifyListeners(evt)\n', '  File "/home/system/scanners/spiderfoot/sflib.py", line 1523, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "/home/system/scanners/spiderfoot/modules/sfp_dnsresolve.py", line 150, in handleEvent\n    self.processHost(match[1], parentEvent, False)\n', '  File "/home/system/scanners/spiderfoot/modules/sfp_dnsresolve.py", line 322, in processHost\n    self.notifyListeners(evt)\n', '  File "/home/system/scanners/spiderfoot/sflib.py", line 1523, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "/home/system/scanners/spiderfoot/modules/sfp_bingsearch.py", line 93, in handleEvent\n    self.notifyListeners(evt)\n', '  File "/home/system/scanners/spiderfoot/sflib.py", line 1523, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "/home/system/scanners/spiderfoot/modules/sfp_dnsresolve.py", line 150, in handleEvent\n    self.processHost(match[1], parentEvent, False)\n', '  File "/home/system/scanners/spiderfoot/modules/sfp_dnsresolve.py", line 326, in processHost\n    self.processDomain(dom, evt)\n', '  File "/home/system/scanners/spiderfoot/modules/sfp_dnsresolve.py", line 345, in processDomain\n    self.notifyListeners(domevt)\n', '  File "/home/system/scanners/spiderfoot/sflib.py", line 1523, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "/home/system/scanners/spiderfoot/modules/sfp_dnsbrute.py", line 130, in handleEvent\n    self.notifyListeners(evt)\n', '  File "/home/system/scanners/spiderfoot/sflib.py", line 1523, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "/home/system/scanners/spiderfoot/modules/sfp_dnsresolve.py", line 210, in handleEvent\n    self.processHost(addr, parentEvent, False)\n', '  File "/home/system/scanners/spiderfoot/modules/sfp_dnsresolve.py", line 322, in processHost\n    self.notifyListeners(evt)\n', '  File "/home/system/scanners/spiderfoot/sflib.py", line 1523, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "/home/system/scanners/spiderfoot/modules/sfp_portscan_tcp.py", line 190, in handleEvent\n    self.sendEvent(self.tryPortWrapper(ipAddr, portArr), event)\n', '  File "/home/system/scanners/spiderfoot/modules/sfp_portscan_tcp.py", line 139, in sendEvent\n    self.notifyListeners(bevt)\n', '  File "/home/system/scanners/spiderfoot/sflib.py", line 1523, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "/home/system/scanners/spiderfoot/modules/sfp_dnsresolve.py", line 120, in handleEvent\n    eventDataHash = self.sf.hashstring(eventData)\n', '  File "/home/system/scanners/spiderfoot/sflib.py", line 374, in hashstring\n    s = string.encode(\'raw_unicode_escape\')\n', "UnicodeDecodeError: 'ascii' codec can't decode byte 0xff in position 33: ordinal not in range(128)\n"]

**Comment by smicallef** [comment]
Did you hit this error from 2.11 or from a recent clone of the repo?

**Comment by mgtremaine** [comment]
From 2.11 and I see that you got it here

commit de018b3b3319902b9ef507c71cbc2ea1f9d4edf0

I just patched and hit re-scan... 

-Mike

**Comment by smicallef** [comment]
Yep, let me know how it goes.

**Comment by mgtremaine** [comment]
Sorry forgot to report back. :/ Pulling directly from GIT over the existing install cleaned this up. Only thing I notices was the rename of the pwaned module threw an error if you tried to re-run an existing scan. Easy to fix. Mark this one closed. -Mike
