### ISSUE TITLE
OSError: Could not read wordlist file 'generic-usernames.txt'

### ISSUE THREAD

**Issue by jayjani007** [smicallef/spiderfoot#1710]
Hi, Getting this error while running the tool

```
Traceback (most recent call last):
  File "/root/Desktop/tools/spiderfoot/spiderfoot/helpers.py", line 370, in usernamesFromWordlists
    with resources.open_text('spiderfoot.dicts', f"{d}.txt", errors='ignore') as dict_file:
AttributeError: module 'resources' has no attribute 'open_text'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "sf.py", line 627, in <module>
    main()
  File "sf.py", line 64, in main
    '_genericusers': ",".join(SpiderFootHelpers.usernamesFromWordlists(['generic-usernames'])),
  File "/root/Desktop/tools/spiderfoot/spiderfoot/helpers.py", line 374, in usernamesFromWordlists
    raise IOError(f"Could not read wordlist file '{d}.txt'") from e
OSError: Could not read wordlist file 'generic-usernames.txt'
```

**Comment by bcoles** [comment]
Which version of Python are you using?

**Comment by jayjani007** [comment]
Hi
It’s Python 3.7.5

**Comment by smicallef** [comment]
Could you verify that the `generic-usernames.txt` file exists in your SpiderFoot installation folder, within `spiderfoot/dicts`?
