### ISSUE TITLE
Can't start SF server

### ISSUE THREAD

**Issue by Quinten0508** [smicallef/spiderfoot#1713]
Using Termux on Android, all requirements from `requirements.txt` have been installed, including `cryptography` and `openssl` 

Python ver: 3.10.5

output:
```
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/spiderfoot-4.0/./sf.py", line 29, in <module>
    from sflib import SpiderFoot
  File "/data/data/com.termux/files/home/spiderfoot-4.0/sflib.py", line 37, in <module>
    import OpenSSL
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import crypto, SSL
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/OpenSSL/crypto.py", line 17, in <module>
    from OpenSSL._util import (
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/OpenSSL/_util.py", line 6, in <module>
    from cryptography.hazmat.bindings.openssl.binding import Binding
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 14, in <module>
    from cryptography.hazmat.bindings._openssl import ffi, lib
ImportError: dlopen failed: cannot locate symbol "ERR_GET_FUNC" referenced by "/data/data/com.termux/files/usr/lib/python3.10/site-packages/cryptography/hazmat/bindings/_openssl.abi3.so"...
```
(edited to fix output formatting)

**Comment by smicallef** [comment]
Have you tried running SpiderFoot on a more "standard" Linux distribution like Debian? We haven't tested it on Android/Termux so not sure if it would even work. Closing this on that basis but please re-open if you experience the same issue on a supported Linux distribution.

**Comment by Quinten0508** [comment]
SpiderFoot runs as expected on supported distributions. Just don't get why it wouldn't work on Termux, seeing as all python dependencies are installed. Does SpiderFoot support or plan to support ARM-based computers? If not, the issue can stay closed.

**Comment by smicallef** [comment]
Agree in theory, but this error appears to be about OpenSSL, specifically within termux (at least based on the path), so it's likely that termux does something special here which perhaps the Python crypto library doesn't like. SpiderFoot runs on ARM machines if they are running other Linux distributions, so this appears to be more termux-specific.

Have you tried a `pip update` in case maybe the python libraries just need updating?
