### ISSUE TITLE
[ERROR] Unhandled exception (BaseException) encountered during scan.

### ISSUE THREAD

**Issue by pythonissam** [smicallef/spiderfoot#173]
Full log:

```plain
Unhandled exception (BaseException) encountered during scan. Please report this as a bug:
['Traceback (most recent call last):\n', '  File "/opt/spiderfoot/sfscan.py", line 188, in startScan\n
self.ts.config[\'_internettlds\'])\n', '  File "/opt/spiderfoot/sflib.py", line 116, in optValueToData\n
self.error("Unable to open option URL, " + val + ": " + str(e))\n', '  File "/opt/spiderfoot/sflib.py", line
298, in error\n    raise BaseException("Internal Error Encountered: " + error)\n', 'BaseException: Internal
Error Encountered: Unable to open option URL, https://publicsuffix.org/list/effective_tld_names.dat:
<urlopen error [Errno 101] Network is unreachable>\n']
```

**Comment by pythonissam** [comment]
Sorry. This was my environment issue.
