### ISSUE TITLE
TLD List Fails to Update

### ISSUE THREAD

**Issue by brassMonkeyz** [smicallef/spiderfoot#1738]
I am using SF 4.0.0 in conjunction with Python 3.10.2. 

While performing a passive search on the target example.com I encountered the following error:
[INFO] sfwebui : Waiting for the scan to initialize...
[INFO] sflib : Downloading configuration data from: https://publicsuffix.org/list/effective_tld_names.dat
[ERROR] sflib : Unable to open option URL, https://publicsuffix.org/list/effective_tld_names.dat: HTTPSConnectionPool(host='publicsuffix.org', port=443): Max retries exceeded with url: /list/effective_tld_names.dat (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)')))
[INFO] sflib : Scan [4DADA4C8] failed: Could not update TLD list
Process Process-1:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/myusrename/Documents/myProjectFolder/spiderfoot/sfscan.py", line 28, in startSpiderFootScanner
    return SpiderFootScanner(*args, **kwargs)
  File "/Users/myusrename/Documents/myProjectFolder/spiderfoot/sfscan.py", line 206, in __init__
    raise ValueError("Could not update TLD list")
ValueError: Could not update TLD list

**Comment by bcoles** [comment]
Are you still receiving this error?

> HTTPSConnectionPool(host='publicsuffix.org', port=443): Max retries exceeded with url: /list/effective_tld_names.dat (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)')))

Certificate validation failed.

**Comment by codemonkeystuff** [comment]
I am getting the same error
Mac OS Ventura - Latest release
Python 3.10
