### ISSUE TITLE
JSONDecodeError

### ISSUE THREAD

**Issue by bxtflxp** [smicallef/spiderfoot#1772]
SpiderFoot      |        ERROR       |        Unhandled exception (JSONDecodeError) encountered during scan. Please report this as a bug: ['Traceback (most recent call last):\n', '  File "/usr/share/spiderfoot/sfscan.py", line 180, in startScan\n    mod.setup(self.ts.sf, self.ts.modconfig[modName])\n', '  File "/usr/share/spiderfoot/modules/sfp_accounts.py", line 80, in setup\n    self.sites = json.loads(content)[\'sites\']\n', '  File "/usr/lib/python3.9/json/__init__.py", line 346, in loads\n    return _default_decoder.decode(s)\n', '  File "/usr/lib/python3.9/json/decoder.py", line 340, in decode\n    raise JSONDecodeError("Extra data", s, end)\n', 'json.decoder.JSONDecodeError: Extra data: line 1 column 4 (char 3)\n']
-- | -- | --

**Comment by bcoles** [comment]
Update to the latest version from GitHub.

Duplicate of #1752.
