### ISSUE TITLE
 | SpiderFoot | ERROR | Unhandled exception (TypeError) encountered during scan. 

### ISSUE THREAD

**Issue by KeKHermanus** [smicallef/spiderfoot#179]
2018-05-12 02:18:43 | SpiderFoot | ERROR | Unhandled exception (TypeError) encountered during scan. Please report this as a bug: ['Traceback (most recent call last):\n', '  File "sfscan.pyc", line 255, in startScan\n', '  File "sflib.pyc", line 1399, in notifyListeners\n', '  File "modules\\sfp_dns.pyc", line 220, in handleEvent\n', '  File "modules\\sfp_dns.pyc", line 387, in processHost\n', '  File "sflib.pyc", line 1399, in notifyListeners\n', '  File "modules\\sfp_vuln.pyc", line 160, in handleEvent\n', "TypeError: unsupported operand type(s) for +: 'NoneType' and 'list'\n"]
-- | -- | -- | --

**Comment by smicallef** [comment]
You're running a pretty old version there.. you should do a git pull to get the latest updates.
