### ISSUE TITLE
Issue at the 201 line

### ISSUE THREAD

**Issue by RobYogi2007** [smicallef/spiderfoot#1806]
Hey, I try to install spiderfoot and at the line 201, an error message (  File "<string>", line 201, in get_source_files
        File "C:\Users\my-computer\AppData\Local\Temp\pip-build-env-ro3bpucs\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 107, in __getattr__
          raise AttributeError(attr)
      AttributeError: cython_sources
      [end of output]  )

With this note at the end : note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

I'm with Python 3.11

thanks in advance 

* https://github.com/smicallef/spiderfoot/issues

**Comment by GMScooter** [comment]
I'm having the same issue:

C:\temp\sf\spiderfoot-4.0> pip3 install -r requirements.txt
Collecting adblockparser<1,>=0.7 (from -r requirements.txt (line 1))
  Using cached adblockparser-0.7-py2.py3-none-any.whl (13 kB)
Collecting dnspython<3,>=2.1.0 (from -r requirements.txt (line 2))
  Using cached dnspython-2.4.2-py3-none-any.whl.metadata (4.9 kB)
Collecting ExifRead<3,>=2.3.2 (from -r requirements.txt (line 3))
  Using cached ExifRead-2.3.2-py3-none-any.whl (38 kB)
Requirement already satisfied: CherryPy<19,>=18.6.1 in c:\users\gmsco\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from -r requirements.txt (line 4)) (18.8.0)
Requirement already satisfied: cherrypy-cors<2,>=1.6 in c:\users\gmsco\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from -r requirements.txt (line 5)) (1.7.0)
Collecting Mako<2,>=1.1.5 (from -r requirements.txt (line 6))
  Using cached Mako-1.3.0-py3-none-any.whl.metadata (2.9 kB)
Requirement already satisfied: beautifulsoup4<5,>=4.10.0 in c:\users\gmsco\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from -r requirements.txt (line 7)) (4.12.2)
Collecting lxml<5,>=4.6.3 (from -r requirements.txt (line 8))
  Using cached lxml-4.9.3-cp311-cp311-win_amd64.whl.metadata (3.9 kB)
Collecting netaddr<1,>=0.8.0 (from -r requirements.txt (line 9))
  Using cached netaddr-0.9.0-py3-none-any.whl.metadata (5.1 kB)
Collecting pysocks<2,>=1.7.1 (from -r requirements.txt (line 10))
  Using cached PySocks-1.7.1-py3-none-any.whl (16 kB)
Requirement already satisfied: requests<3,>=2.26.0 in c:\users\gmsco\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from -r requirements.txt (line 11)) (2.31.0)
Collecting ipwhois<1.2.0,>=1.1.0 (from -r requirements.txt (line 12))
  Using cached ipwhois-1.1.0-py2.py3-none-any.whl (74 kB)
Collecting ipaddr<3,>=2.2.0 (from -r requirements.txt (line 13))
  Using cached ipaddr-2.2.0.tar.gz (26 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting phonenumbers<9,>=8.12.34 (from -r requirements.txt (line 14))
  Using cached phonenumbers-8.13.24-py2.py3-none-any.whl.metadata (11 kB)
Collecting pygexf<0.3,>=0.2.2 (from -r requirements.txt (line 15))
  Using cached pygexf-0.2.2.tar.gz (5.1 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting PyPDF2<2,>=1.26.0 (from -r requirements.txt (line 16))
  Using cached PyPDF2-1.28.6-py3-none-any.whl (87 kB)
Collecting python-whois<0.8,>=0.7.3 (from -r requirements.txt (line 17))
  Using cached python-whois-0.7.3.tar.gz (91 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting secure<0.4.0,>=0.3.0 (from -r requirements.txt (line 18))
  Using cached secure-0.3.0-py3-none-any.whl (9.6 kB)
Collecting pyOpenSSL<22,>=21.0.0 (from -r requirements.txt (line 19))
  Using cached pyOpenSSL-21.0.0-py2.py3-none-any.whl (55 kB)
Collecting python-docx<0.9,>=0.8.11 (from -r requirements.txt (line 20))
  Using cached python-docx-0.8.11.tar.gz (5.6 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting python-pptx<0.7,>=0.6.21 (from -r requirements.txt (line 21))
  Using cached python_pptx-0.6.23-py3-none-any.whl.metadata (18 kB)
Collecting networkx<2.7,>=2.6.3 (from -r requirements.txt (line 22))
  Using cached networkx-2.6.3-py3-none-any.whl (1.9 MB)
Collecting cryptography<4,>=3.4.8 (from -r requirements.txt (line 23))
  Using cached cryptography-3.4.8-cp36-abi3-win_amd64.whl (1.6 MB)
Collecting publicsuffixlist<0.8,>=0.7.9 (from -r requirements.txt (line 24))
  Using cached publicsuffixlist-0.7.14-py2.py3-none-any.whl (95 kB)
Collecting openpyxl<4,>=3.0.9 (from -r requirements.txt (line 25))
  Using cached openpyxl-3.1.2-py2.py3-none-any.whl (249 kB)
Collecting pyyaml<6,>=5.3.1 (from -r requirements.txt (line 26))
  Using cached PyYAML-5.4.1.tar.gz (175 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [68 lines of output]
      C:\Users\gmsco\AppData\Local\Temp\pip-build-env-9kx4tp4d\overlay\Lib\site-packages\setuptools\config\setupcfg.py:293: _DeprecatedConfig: Deprecated config in `setup.cfg`
      !!

              ********************************************************************************
              The license_file parameter is deprecated, use license_files instead.

              This deprecation is overdue, please update your project and remove deprecated
              calls to avoid build errors in the future.

              See https://setuptools.pypa.io/en/latest/userguide/declarative_config.html for details.
              ********************************************************************************

      !!
        parsed = self.parsers.get(option_name, lambda x: x)(value)
      running egg_info
      writing lib3\PyYAML.egg-info\PKG-INFO
      writing dependency_links to lib3\PyYAML.egg-info\dependency_links.txt
      writing top-level names to lib3\PyYAML.egg-info\top_level.txt
      Traceback (most recent call last):
        File "C:\Users\gmsco\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\gmsco\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\gmsco\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\gmsco\AppData\Local\Temp\pip-build-env-9kx4tp4d\overlay\Lib\site-packages\setuptools\build_meta.py", line 355, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\gmsco\AppData\Local\Temp\pip-build-env-9kx4tp4d\overlay\Lib\site-packages\setuptools\build_meta.py", line 325, in _get_build_requires
          self.run_setup()
        File "C:\Users\gmsco\AppData\Local\Temp\pip-build-env-9kx4tp4d\overlay\Lib\site-packages\setuptools\build_meta.py", line 341, in run_setup
          exec(code, locals())
        File "<string>", line 271, in <module>
        File "C:\Users\gmsco\AppData\Local\Temp\pip-build-env-9kx4tp4d\overlay\Lib\site-packages\setuptools\__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\gmsco\AppData\Local\Temp\pip-build-env-9kx4tp4d\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "C:\Users\gmsco\AppData\Local\Temp\pip-build-env-9kx4tp4d\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
          dist.run_commands()
        File "C:\Users\gmsco\AppData\Local\Temp\pip-build-env-9kx4tp4d\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "C:\Users\gmsco\AppData\Local\Temp\pip-build-env-9kx4tp4d\overlay\Lib\site-packages\setuptools\dist.py", line 989, in run_command
          super().run_command(command)
        File "C:\Users\gmsco\AppData\Local\Temp\pip-build-env-9kx4tp4d\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\gmsco\AppData\Local\Temp\pip-build-env-9kx4tp4d\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 318, in run
          self.find_sources()
        File "C:\Users\gmsco\AppData\Local\Temp\pip-build-env-9kx4tp4d\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 326, in find_sources
          mm.run()
        File "C:\Users\gmsco\AppData\Local\Temp\pip-build-env-9kx4tp4d\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 548, in run
          self.add_defaults()
        File "C:\Users\gmsco\AppData\Local\Temp\pip-build-env-9kx4tp4d\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 586, in add_defaults
          sdist.add_defaults(self)
        File "C:\Users\gmsco\AppData\Local\Temp\pip-build-env-9kx4tp4d\overlay\Lib\site-packages\setuptools\command\sdist.py", line 113, in add_defaults
          super().add_defaults()
        File "C:\Users\gmsco\AppData\Local\Temp\pip-build-env-9kx4tp4d\overlay\Lib\site-packages\setuptools\_distutils\command\sdist.py", line 251, in add_defaults
          self._add_defaults_ext()
        File "C:\Users\gmsco\AppData\Local\Temp\pip-build-env-9kx4tp4d\overlay\Lib\site-packages\setuptools\_distutils\command\sdist.py", line 336, in _add_defaults_ext
          self.filelist.extend(build_ext.get_source_files())
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "<string>", line 201, in get_source_files
        File "C:\Users\gmsco\AppData\Local\Temp\pip-build-env-9kx4tp4d\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 107, in __getattr__
          raise AttributeError(attr)
      AttributeError: cython_sources
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by gabrielmvas** [comment]
Same issue here, both locally and through docker compose I'm getting the same error

```
Collecting pyyaml<6,>=5.4.1 (from -r requirements.txt (line 26))
  Downloading PyYAML-5.4.1.tar.gz (175 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 175.1/175.1 kB 10.3 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [54 lines of output]
      running egg_info
      writing lib3/PyYAML.egg-info/PKG-INFO
      writing dependency_links to lib3/PyYAML.egg-info/dependency_links.txt
      writing top-level names to lib3/PyYAML.egg-info/top_level.txt
      Traceback (most recent call last):
        File "/home/gabi/.local/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/gabi/.local/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/gabi/.local/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-t427cy0o/overlay/local/lib/python3.11/dist-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-t427cy0o/overlay/local/lib/python3.11/dist-packages/setuptools/build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-t427cy0o/overlay/local/lib/python3.11/dist-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 271, in <module>
        File "/tmp/pip-build-env-t427cy0o/overlay/local/lib/python3.11/dist-packages/setuptools/__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-t427cy0o/overlay/local/lib/python3.11/dist-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-t427cy0o/overlay/local/lib/python3.11/dist-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/tmp/pip-build-env-t427cy0o/overlay/local/lib/python3.11/dist-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/tmp/pip-build-env-t427cy0o/overlay/local/lib/python3.11/dist-packages/setuptools/dist.py", line 963, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-t427cy0o/overlay/local/lib/python3.11/dist-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-t427cy0o/overlay/local/lib/python3.11/dist-packages/setuptools/command/egg_info.py", line 321, in run
          self.find_sources()
        File "/tmp/pip-build-env-t427cy0o/overlay/local/lib/python3.11/dist-packages/setuptools/command/egg_info.py", line 329, in find_sources
          mm.run()
        File "/tmp/pip-build-env-t427cy0o/overlay/local/lib/python3.11/dist-packages/setuptools/command/egg_info.py", line 551, in run
          self.add_defaults()
        File "/tmp/pip-build-env-t427cy0o/overlay/local/lib/python3.11/dist-packages/setuptools/command/egg_info.py", line 589, in add_defaults
          sdist.add_defaults(self)
        File "/tmp/pip-build-env-t427cy0o/overlay/local/lib/python3.11/dist-packages/setuptools/command/sdist.py", line 112, in add_defaults
          super().add_defaults()
        File "/tmp/pip-build-env-t427cy0o/overlay/local/lib/python3.11/dist-packages/setuptools/_distutils/command/sdist.py", line 251, in add_defaults
          self._add_defaults_ext()
        File "/tmp/pip-build-env-t427cy0o/overlay/local/lib/python3.11/dist-packages/setuptools/_distutils/command/sdist.py", line 336, in _add_defaults_ext
          self.filelist.extend(build_ext.get_source_files())
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "<string>", line 201, in get_source_files
        File "/tmp/pip-build-env-t427cy0o/overlay/local/lib/python3.11/dist-packages/setuptools/_distutils/cmd.py", line 107, in __getattr__
          raise AttributeError(attr)
      AttributeError: cython_sources
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

```

**Comment by tiiraluoto** [comment]
Me too! I am using Linux

**Comment by darkb0ts** [comment]
try this ```pip install --upgrade setuptools wheel``` and ```pip install --no-cache-dir spiderfoot```

**Comment by N3PH1L4X** [comment]
I fixed it with these commands
$ pip install "cython<3.0.0" wheel
$ pip install "pyyaml==5.4.1" --no-build-isolation
$ pip install -r requirements.txt
source: https://stackoverflow.com/questions/77490435/attributeerror-cython-sources

**Comment by imonkolina-ctrl** [comment]
Thanks for this thread. I encountered the same problem and tried to solve it through the last solution. But then I got this below. Any chance you could help? 

>   error: subprocess-exited-with-error
> 
>   × python setup.py egg_info did not run successfully.
>   │ exit code: 1
>   ╰─> [5 lines of output]
>       /tmp/pip-install-od825taf/lxml_c475090bf1154bb49941effd66e83e8f/setup.py:67: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
>         import pkg_resources
>       Building lxml version 4.9.4.
>       Building without Cython.
>       Error: Please make sure the libxml2 and libxslt development packages are installed.
>       [end of output]
