### ISSUE TITLE
Starting up but Error on start

### ISSUE THREAD

**Issue by Satanaelcode** [smicallef/spiderfoot#1810]
**/// GENERAL INFO ///**

Starting a Search with data triggered this Error

- PY3-VERSION: 3.9.2
- PY2-VERSION: 2.7.18
- APP-VERSION: 3.0

**/// ERROR CODE ///**

`
['Traceback (most recent call last):\n', '  File "/usr/share/spiderfoot/sfscan.py", line 180, in startScan\n    mod.setup(self.ts.sf, self.ts.modconfig[modName])\n', '  File "/usr/share/spiderfoot/modules/sfp_accounts.py", line 80, in setup\n    self.sites = json.loads(content)[\'sites\']\n', '  File "/usr/lib/python3.9/json/__init__.py", line 346, in loads\n    return _default_decoder.decode(s)\n', '  File "/usr/lib/python3.9/json/decoder.py", line 340, in decode\n    raise JSONDecodeError("Extra data", s, end)\n', 'json.decoder.JSONDecodeError: Extra data: line 1 column 4 (char 3)\n']`

**Comment by bcoles** [comment]
This should be patched in the latest version on GitHub:

```
git clone https://github.com/smicallef/spiderfoot
```

No official release of SpiderFoot has been released since.
