### ISSUE TITLE
SpiderFoot searches don't return elements

### ISSUE THREAD

**Issue by garcia121diego** [smicallef/spiderfoot#1829]
Hey all, I recently set up SpiderFoot on my Mac, had to go through installing all the required packets i.e brew, git...
Got SpiderFoot running, and I could pull up the GUI on my browser, but no matter what I search none of my search return any elements. I have tried searching my own personal info, domain names like google.com and their IP address 8.8.8.8, or whatever the YouTube tutorial videos are using, but no mater what I search, I get no returns. I am thinking maybe I created some issues on my pathways while installing. I tried finding a solution online but nothing. 

If anyone has any advice or insight on how I might be able to solve this I'll consider naming my first child after you, Thanks

**Comment by bcoles** [comment]
Which use case or module did you use for your scan? Are there any errors in the terminal or scan logs?

**Comment by garcia121diego** [comment]
I used the "All" option since it's my first searcher, but I did set some API keys for some of the modules. 

And I get a good amount of errors this is the first one: 
[ERROR] sflib : Exception (OSError) in module sfp_tool_wappalyzer.Traceback (most recent call last):

~/spiderfoot/spiderfoot/db.py", line 318, in __init__
sqlite3.OperationalError: unable to open database file

and the it just follows on with this:

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/usr/spiderfoot/spiderfoot/plugin.py", line 502, in threadWorker
  File "/Users/usr/spiderfoot/spiderfoot/db.py", line 320, in __init__
OSError: Error connecting to internal database /Users/usr/.spiderfoot//spiderspiderfoot.db

and the followed by several other "The above exception was the direct cause of the following exception:" messages

**Comment by bcoles** [comment]
Probably a dupe of #1733. There is currently no fix for this on OSX.

**Comment by garcia121diego** [comment]
Sounds good, thank you so much
