### ISSUE TITLE
Docker build fails

### ISSUE THREAD

**Issue by sys-walker** [smicallef/spiderfoot#1832]
similar to https://github.com/smicallef/spiderfoot/issues/1804 but in docker

```
 => ERROR [spiderfoot build 8/8] RUN pip3 install -r "requirements.txt"   12.5s
------
 > [spiderfoot build 8/8] RUN pip3 install -r "requirements.txt":
0.434 Collecting adblockparser<1,>=0.7 (from -r requirements.txt (line 1))
0.496   Downloading adblockparser-0.7-py2.py3-none-any.whl (13 kB)
0.530 Collecting dnspython<3,>=2.1.0 (from -r requirements.txt (line 2))
0.550   Downloading dnspython-2.4.2-py3-none-any.whl.metadata (4.9 kB)
0.690 Collecting ExifRead<3,>=2.3.2 (from -r requirements.txt (line 3))
0.715   Downloading ExifRead-2.3.2-py3-none-any.whl (38 kB)
0.810 Collecting CherryPy<19,>=18.6.1 (from -r requirements.txt (line 4))
0.835   Downloading CherryPy-18.9.0-py3-none-any.whl.metadata (8.8 kB)
0.983 Collecting cherrypy-cors<2,>=1.6 (from -r requirements.txt (line 5))
1.003   Downloading cherrypy_cors-1.7.0-py3-none-any.whl.metadata (3.1 kB)
1.051 Collecting Mako<2,>=1.1.5 (from -r requirements.txt (line 6))
1.070   Downloading Mako-1.3.0-py3-none-any.whl.metadata (2.9 kB)
1.109 Collecting beautifulsoup4<5,>=4.10.0 (from -r requirements.txt (line 7))
1.128   Downloading beautifulsoup4-4.12.2-py3-none-any.whl (142 kB)
1.153      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 143.0/143.0 kB 6.0 MB/s eta 0:00:00
1.335 Collecting lxml<5,>=4.6.3 (from -r requirements.txt (line 8))
1.452   Downloading lxml-4.9.4-cp38-cp38-musllinux_1_1_aarch64.whl.metadata (3.7 kB)
1.493 Collecting netaddr<1,>=0.8.0 (from -r requirements.txt (line 9))
1.511   Downloading netaddr-0.9.0-py3-none-any.whl.metadata (5.1 kB)
1.543 Collecting pysocks<2,>=1.7.1 (from -r requirements.txt (line 10))
1.560   Downloading PySocks-1.7.1-py3-none-any.whl (16 kB)
1.612 Collecting requests<3,>=2.26.0 (from -r requirements.txt (line 11))
1.628   Downloading requests-2.31.0-py3-none-any.whl.metadata (4.6 kB)
1.654 Collecting ipwhois<1.2.0,>=1.1.0 (from -r requirements.txt (line 12))
1.674   Downloading ipwhois-1.1.0-py2.py3-none-any.whl (74 kB)
1.683      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 74.5/74.5 kB 8.9 MB/s eta 0:00:00
1.705 Collecting ipaddr<3,>=2.2.0 (from -r requirements.txt (line 13))
1.723   Downloading ipaddr-2.2.0.tar.gz (26 kB)
1.731   Installing build dependencies: started
3.006   Installing build dependencies: finished with status 'done'
3.007   Getting requirements to build wheel: started
3.103   Getting requirements to build wheel: finished with status 'done'
3.105   Preparing metadata (pyproject.toml): started
3.207   Preparing metadata (pyproject.toml): finished with status 'done'
3.270 Collecting phonenumbers<9,>=8.12.34 (from -r requirements.txt (line 14))
3.290   Downloading phonenumbers-8.13.27-py2.py3-none-any.whl.metadata (11 kB)
3.437 Collecting pygexf<0.3,>=0.2.2 (from -r requirements.txt (line 15))
3.457   Downloading pygexf-0.2.2.tar.gz (5.1 kB)
3.467   Installing build dependencies: started
4.368   Installing build dependencies: finished with status 'done'
4.369   Getting requirements to build wheel: started
4.463   Getting requirements to build wheel: finished with status 'done'
4.465   Preparing metadata (pyproject.toml): started
4.567   Preparing metadata (pyproject.toml): finished with status 'done'
4.611 Collecting PyPDF2<2,>=1.26.0 (from -r requirements.txt (line 16))
4.629   Downloading PyPDF2-1.28.6-py3-none-any.whl (87 kB)
4.640      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 87.1/87.1 kB 10.9 MB/s eta 0:00:00
4.663 Collecting python-whois<0.8,>=0.7.3 (from -r requirements.txt (line 17))
4.681   Downloading python-whois-0.7.3.tar.gz (91 kB)
4.692      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 91.5/91.5 kB 11.3 MB/s eta 0:00:00
4.699   Installing build dependencies: started
5.617   Installing build dependencies: finished with status 'done'
5.618   Getting requirements to build wheel: started
5.712   Getting requirements to build wheel: finished with status 'done'
5.714   Preparing metadata (pyproject.toml): started
5.818   Preparing metadata (pyproject.toml): finished with status 'done'
5.847 Collecting secure<0.4.0,>=0.3.0 (from -r requirements.txt (line 18))
5.865   Downloading secure-0.3.0-py3-none-any.whl (9.6 kB)
5.902 Collecting pyOpenSSL<22,>=21.0.0 (from -r requirements.txt (line 19))
5.918   Downloading pyOpenSSL-21.0.0-py2.py3-none-any.whl (55 kB)
5.930      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 55.1/55.1 kB 10.3 MB/s eta 0:00:00
5.955 Collecting python-docx<0.9,>=0.8.11 (from -r requirements.txt (line 20))
5.976   Downloading python-docx-0.8.11.tar.gz (5.6 MB)
6.611      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.6/5.6 MB 8.9 MB/s eta 0:00:00
6.759   Installing build dependencies: started
7.704   Installing build dependencies: finished with status 'done'
7.705   Getting requirements to build wheel: started
7.813   Getting requirements to build wheel: finished with status 'done'
7.815   Preparing metadata (pyproject.toml): started
7.929   Preparing metadata (pyproject.toml): finished with status 'done'
7.958 Collecting python-pptx<0.7,>=0.6.21 (from -r requirements.txt (line 21))
7.978   Downloading python_pptx-0.6.23-py3-none-any.whl.metadata (18 kB)
8.018 Collecting networkx<2.7,>=2.6.3 (from -r requirements.txt (line 22))
8.037   Downloading networkx-2.6.3-py3-none-any.whl (1.9 MB)
8.221      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.9/1.9 MB 10.6 MB/s eta 0:00:00
8.445 Collecting cryptography<4,>=3.4.8 (from -r requirements.txt (line 23))
8.466   Downloading cryptography-3.4.8-cp36-abi3-musllinux_1_1_aarch64.whl (3.1 MB)
8.779      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 10.1 MB/s eta 0:00:00
8.853 Collecting publicsuffixlist<0.8,>=0.7.9 (from -r requirements.txt (line 24))
8.871   Downloading publicsuffixlist-0.7.14-py2.py3-none-any.whl (95 kB)
8.887      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 95.6/95.6 kB 7.2 MB/s eta 0:00:00
8.923 Collecting openpyxl<4,>=3.0.9 (from -r requirements.txt (line 25))
8.943   Downloading openpyxl-3.1.2-py2.py3-none-any.whl (249 kB)
8.969      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 250.0/250.0 kB 10.0 MB/s eta 0:00:00
9.015 Collecting pyyaml<6,>=5.4.1 (from -r requirements.txt (line 26))
9.035   Downloading PyYAML-5.4.1.tar.gz (175 kB)
9.055      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 175.1/175.1 kB 9.0 MB/s eta 0:00:00
9.143   Installing build dependencies: started
12.13   Installing build dependencies: finished with status 'done'
12.13   Getting requirements to build wheel: started
12.28   Getting requirements to build wheel: finished with status 'error'
12.28   error: subprocess-exited-with-error
12.28   
12.28   × Getting requirements to build wheel did not run successfully.
12.28   │ exit code: 1
12.28   ╰─> [48 lines of output]
12.28       running egg_info
12.28       writing lib3/PyYAML.egg-info/PKG-INFO
12.28       writing dependency_links to lib3/PyYAML.egg-info/dependency_links.txt
12.28       writing top-level names to lib3/PyYAML.egg-info/top_level.txt
12.28       Traceback (most recent call last):
12.28         File "/opt/venv/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
12.28           main()
12.28         File "/opt/venv/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
12.28           json_out['return_val'] = hook(**hook_input['kwargs'])
12.28         File "/opt/venv/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
12.28           return hook(config_settings)
12.28         File "/tmp/pip-build-env-0dmj26_y/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
12.28           return self._get_build_requires(config_settings, requirements=['wheel'])
12.28         File "/tmp/pip-build-env-0dmj26_y/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
12.28           self.run_setup()
12.28         File "/tmp/pip-build-env-0dmj26_y/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 311, in run_setup
12.28           exec(code, locals())
12.28         File "<string>", line 271, in <module>
12.28         File "/tmp/pip-build-env-0dmj26_y/overlay/lib/python3.8/site-packages/setuptools/__init__.py", line 103, in setup
12.28           return distutils.core.setup(**attrs)
12.28         File "/tmp/pip-build-env-0dmj26_y/overlay/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 185, in setup
12.28           return run_commands(dist)
12.28         File "/tmp/pip-build-env-0dmj26_y/overlay/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
12.28           dist.run_commands()
12.28         File "/tmp/pip-build-env-0dmj26_y/overlay/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
12.28           self.run_command(cmd)
12.28         File "/tmp/pip-build-env-0dmj26_y/overlay/lib/python3.8/site-packages/setuptools/dist.py", line 963, in run_command
12.28           super().run_command(command)
12.28         File "/tmp/pip-build-env-0dmj26_y/overlay/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
12.28           cmd_obj.run()
12.28         File "/tmp/pip-build-env-0dmj26_y/overlay/lib/python3.8/site-packages/setuptools/command/egg_info.py", line 321, in run
12.28           self.find_sources()
12.28         File "/tmp/pip-build-env-0dmj26_y/overlay/lib/python3.8/site-packages/setuptools/command/egg_info.py", line 329, in find_sources
12.28           mm.run()
12.28         File "/tmp/pip-build-env-0dmj26_y/overlay/lib/python3.8/site-packages/setuptools/command/egg_info.py", line 551, in run
12.28           self.add_defaults()
12.28         File "/tmp/pip-build-env-0dmj26_y/overlay/lib/python3.8/site-packages/setuptools/command/egg_info.py", line 589, in add_defaults
12.28           sdist.add_defaults(self)
12.28         File "/tmp/pip-build-env-0dmj26_y/overlay/lib/python3.8/site-packages/setuptools/command/sdist.py", line 112, in add_defaults
12.28           super().add_defaults()
12.28         File "/tmp/pip-build-env-0dmj26_y/overlay/lib/python3.8/site-packages/setuptools/_distutils/command/sdist.py", line 251, in add_defaults
12.28           self._add_defaults_ext()
12.28         File "/tmp/pip-build-env-0dmj26_y/overlay/lib/python3.8/site-packages/setuptools/_distutils/command/sdist.py", line 336, in _add_defaults_ext
12.28           self.filelist.extend(build_ext.get_source_files())
12.28         File "<string>", line 201, in get_source_files
12.28         File "/tmp/pip-build-env-0dmj26_y/overlay/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 107, in __getattr__
12.28           raise AttributeError(attr)
12.28       AttributeError: cython_sources
12.28       [end of output]
12.28   
12.28   note: This error originates from a subprocess, and is likely not a problem with pip.
12.29 error: subprocess-exited-with-error
12.29 
12.29 × Getting requirements to build wheel did not run successfully.
12.29 │ exit code: 1
12.29 ╰─> See above for output.
12.29 
12.29 note: This error originates from a subprocess, and is likely not a problem with pip.
------
failed to solve: process "/bin/sh -c pip3 install -r \"$REQUIREMENTS\"" did not complete successfully: exit code: 1
```

**Comment by edwardcjohnson** [comment]
the build was successful for me. I just followed the steps shown in: https://asciinema.org/a/165187

**Comment by Hem7S** [comment]
I was having the same problem, I was downloading the stable release build. Getting the development build release works for me.

**Comment by joachimdostal** [comment]
I also followed the steps from https://asciinema.org/a/165187 (thanks a lot for that) on Debian Bullseye and need only to change python ./sfcli.py -s http://localhost:5009 to python**3** ./sfcli.py -s http://localhost:5009. But this could be an local issue with my "python installationS".
