### ISSUE TITLE
Unhandled exception (error) encountered during scan

### ISSUE THREAD

**Issue by ADL7** [smicallef/spiderfoot#184]
While scanning, I received the following error message: 
-------------------------

Unhandled exception (error) encountered during scan. Please report this as a bug:
Traceback (most recent call last):
  File "/home/spiderfoot/sfscan.py", line 265, in startScan
    psMod.notifyListeners(firstEvent)
  File "/home/spiderfoot/sflib.py", line 1527, in notifyListeners
    listener.handleEvent(sfEvent)
  File "/home/spiderfoot/modules/sfp_dnsresolve.py", line 222, in handleEvent
    self.processHost(addr, parentEvent, False)
  File "/home/spiderfoot/modules/sfp_dnsresolve.py", line 338, in processHost
    self.processDomain(dom, evt)
  File "/home/spiderfoot/modules/sfp_dnsresolve.py", line 357, in processDomain
    self.notifyListeners(domevt)
  File "/home/spiderfoot/sflib.py", line 1527, in notifyListeners
    listener.handleEvent(sfEvent)
  File "/home/spiderfoot/modules/sfp_dnsbrute.py", line 131, in handleEvent
    self.notifyListeners(evt)
  File "/home/spiderfoot/sflib.py", line 1527, in notifyListeners
    listener.handleEvent(sfEvent)
  File "/home/spiderfoot/modules/sfp_dnsresolve.py", line 222, in handleEvent
    self.processHost(addr, parentEvent, False)
  File "/home/spiderfoot/modules/sfp_dnsresolve.py", line 334, in processHost
    self.notifyListeners(evt)
  File "/home/spiderfoot/sflib.py", line 1527, in notifyListeners
    listener.handleEvent(sfEvent)
  File "/home/spiderfoot/modules/sfp_robtex.py", line 167, in handleEvent
    self.notifyListeners(evt)
  File "/home/spiderfoot/sflib.py", line 1527, in notifyListeners
    listener.handleEvent(sfEvent)
  File "/home/spiderfoot/modules/sfp_badipscom.py", line 246, in handleEvent
    url = self.lookupItem(cid, typeId, eventData)
  File "/home/spiderfoot/modules/sfp_badipscom.py", line 197, in lookupItem
    return self.resourceList(cid, target, itemType)
  File "/home/spiderfoot/modules/sfp_badipscom.py", line 183, in resourceList
    re.match(rxTgt, line, re.IGNORECASE):
  File "/usr/lib/python2.7/re.py", line 141, in match
    return _compile(pattern, flags).match(string)
  File "/usr/lib/python2.7/re.py", line 251, in _compile
    raise error, v # invalid expression
error: nothing to repeat

----------------------
 What could be the cause of this error message?

**Comment by lvh** [comment]
@smicallef Was the fix the decode("string_escape") calls that were added? How's that work?

I ask because part of me wants to help moving spiderfoot to work on both Py2 and Py3, and `.decode("string_escape")` doesn't work on Python 3. `.decode("unicode_escape")` often does nearly the same thing. Also I started debugging this on Friday and got up to "looks like `r"{5}"`" so also partially for my own edification :)

**Comment by marxenegls** [comment]
i got something similar 

Time | Component | Type | Event
-- | -- | -- | --
2018-05-30 06:11:01 | SpiderFoot | STATUS | Scan [92C55B63] failed: invalid literal for int() with base 10: ''
2018-05-30 06:11:01 | SpiderFoot | ERROR | Unhandled exception (ValueError) encountered during scan. Please report this as a bug: ['Traceback (most recent call last):\n', '  File "/opt/spiderfoot/sfscan.py", line 213, in startScan\n    mod.setup(self.ts.sf, self.ts.modconfig[modName])\n', '  File "/opt/spiderfoot/modules/sfp_portscan_tcp.py", line 71, in setup\n    self.portlist = [int(x) for x in self.portlist]\n', "ValueError: invalid literal for int() with base 10: ''\n"]

**Comment by ADL7** [comment]
As of commit eb2f0299fe46b4d83a6db6c2c154047084d1a60e, I still have the same error 13 minutes into the scan. I am testing this on ' latacora.com '.

**Comment by smicallef** [comment]
@lvh Yep that was the fix.

@ADL7 Can you pull from master? The fix was after that commit.

**Comment by lvh** [comment]
@smicallef I'm seeing that linked commit as GitHub master right now, and it includes the commit I mentioned with the string_escape changes.

**Comment by smicallef** [comment]
Are you getting the exact same error with that fix applied?

**Comment by ADL7** [comment]
@smicallef yes. It is the same error. I pulled from master this morning as well.

**Comment by smicallef** [comment]
Could you paste the error you are getting? Even a subtle difference could be important, because theoretically it shouldn't happen any more :)

**Comment by ADL7** [comment]
@smicallef no problem. I posted the error below: 

[!] SpiderFoot: Unhandled exception (error) encountered during scan. Please report this as a bug: ['Traceback (most recent call last):\n', '  File "/home/spiderfoot/sfscan.py", line 265, in startScan\n    psMod.notifyListeners(firstEvent)\n', '  File "/home/spiderfoot/sflib.py", line 1527, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "/home/spiderfoot/modules/sfp_dnsresolve.py", line 222, in handleEvent\n    self.processHost(addr, parentEvent, False)\n', '  File "/home/spiderfoot/modules/sfp_dnsresolve.py", line 338, in processHost\n    self.processDomain(dom, evt)\n', '  File "/home/spiderfoot/modules/sfp_dnsresolve.py", line 357, in processDomain\n    self.notifyListeners(domevt)\n', '  File "/home/spiderfoot/sflib.py", line 1527, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "/home/spiderfoot/modules/sfp_dnsbrute.py", line 131, in handleEvent\n    self.notifyListeners(evt)\n', '  File "/home/spiderfoot/sflib.py", line 1527, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "/home/spiderfoot/modules/sfp_dnsresolve.py", line 222, in handleEvent\n    self.processHost(addr, parentEvent, False)\n', '  File "/home/spiderfoot/modules/sfp_dnsresolve.py", line 334, in processHost\n    self.notifyListeners(evt)\n', '  File "/home/spiderfoot/sflib.py", line 1527, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "/home/spiderfoot/modules/sfp_robtex.py", line 167, in handleEvent\n    self.notifyListeners(evt)\n', '  File "/home/spiderfoot/sflib.py", line 1527, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "/home/spiderfoot/modules/sfp_badipscom.py", line 246, in handleEvent\n    url = self.lookupItem(cid, typeId, eventData)\n', '  File "/home/spiderfoot/modules/sfp_badipscom.py", line 197, in lookupItem\n    return self.resourceList(cid, target, itemType)\n', '  File "/home/spiderfoot/modules/sfp_badipscom.py", line 183, in resourceList\n    re.match(rxTgt, line, re.IGNORECASE):\n', '  File "/usr/lib/python2.7/re.py", line 141, in match\n    return _compile(pattern, flags).match(string)\n', '  File "/usr/lib/python2.7/re.py", line 251, in _compile\n    raise error, v # invalid expression\n', 'error: nothing to repeat\n']

**Comment by smicallef** [comment]
Thanks. This is a different issue to the one my fix was addressing (that one was about a bogus escape character), so I'll take a look. I thought my fix addressed this as well, but clearly not.

**Comment by marxenegls** [comment]
ADL7 
are you using any sort of proxy ?

**Comment by lvh** [comment]
@marxenegls (I'm working with @ADL7: no proxies.)
