### ISSUE TITLE
sfp_filemeta: No module named 'exceptions'

### ISSUE THREAD

**Issue by mattmayer94** [smicallef/spiderfoot#1848]
I'm trying to start the server to launch the web UI, but I'm receiving an error 

CRITICAL:spiderfoot.__main__:Failed to load module sfp_filemeta: No module named 'exceptions'

2024-03-02 08:34:35,727 [CRITICAL] sf : Failed to load module sfp_filemeta: No module named 'exceptions'

'exceptions' does not appear in sfp_filemeta so it must be from a dependency. 

What am I missing?

**Comment by SHL0MS** [comment]
same error

**Comment by darkb0ts** [comment]
what is your python version cmd:```python --version``` and paste your error

**Comment by distinguishedVagrant** [comment]
Same issue here, running python 3.11.2 on debian xfce disposable in qubes.os.

(myenv) user@disp9558:/snap/spiderfoot/current$ python3 sf.py -l 127.0.0.1
2024-06-06 19:35:35,307 [CRITICAL] sf : Failed to load modules: No module named 'exceptions'
Traceback (most recent call last):
  File "/snap/spiderfoot/133/sf.py", line 144, in main
    sfModules = SpiderFootHelpers.loadModulesAsDict(mod_dir, ['sfp_template.py'])
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/snap/spiderfoot/133/spiderfoot/helpers.py", line 161, in loadModulesAsDict
    mod = __import__('modules.' + modName, globals(), locals(), [modName])
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/snap/spiderfoot/133/modules/sfp_filemeta.py", line 19, in <module>
    import docx
  File "/home/user/myenv/lib/python3.11/site-packages/docx.py", line 30, in <module>
    from exceptions import PendingDeprecationWarning
ModuleNotFoundError: No module named 'exceptions'

**Comment by fmendes-e** [comment]
same error here.

**Comment by fmendes-e** [comment]
try this, in my case was cython, when i run pip3 install -r requirements return something related with, so i install this guy, uninstall pyyaml and install again.

groot@debian:~/spiderfoot-4.0$ pip3 install "cython<3.0.0" wheel --break-system-packages
pip uninstall pyyaml --break-system-packages
pip install "pyyaml==5.4.1" --no-build-isolation --break-system-packages
pip3 install -r requirements.txt --break-system-packages

after all this is returning other error with cryptography not compatible to other modules, but now i can run spiderfoot xD

**Comment by R4teL-M** [comment]
same error ,After using the fmendes-e method, the startup was successful

> 试试这个，在我的情况下是 cython，当我运行 pip3 install -r requirements 返回与之相关的东西，所以我安装了这个家伙，卸载 pyyaml 并再次安装。
> 
> groot@debian:~/spiderfoot-4.0$ pip3 安装“cython<3.0.0” wheel --break-system-packages pip 卸载 pyyaml --break-system-packages pip 安装“pyyaml==5.4.1” --no-build-isolation --break-system-packages pip3 安装 -r requirements.txt --break-system-packages
> 
> 毕竟这返回了其他错误，加密与其他模块不兼容，但现在我可以运行 spiderfoot xD

**Comment by axellfumioo** [comment]
> try this, in my case was cython, when i run pip3 install -r requirements return something related with, so i install this guy, uninstall pyyaml and install again.
> 
> groot@debian:~/spiderfoot-4.0$ pip3 install "cython<3.0.0" wheel --break-system-packages pip uninstall pyyaml --break-system-packages pip install "pyyaml==5.4.1" --no-build-isolation --break-system-packages pip3 install -r requirements.txt --break-system-packages
> 
> after all this is returning other error with cryptography not compatible to other modules, but now i can run spiderfoot xD

this method works for me. thank you

**Comment by AndreC10002** [comment]
If 'cython' is required, it should be mentioned somewhere in the documentation. That doesn't seem to me like the right solution and not a path I want to take.
Would appreciate advice from SF maintainers.
Thank you.

**Comment by AndreC10002** [comment]
Actually, the solution is to install 'python-docx', instead of 'docx'.

**Comment by Mrsharmax** [comment]
> Actually, the solution is to install 'python-docx', instead of 'docx'.

This worked.

**Comment by bigsam-666** [comment]
ThanX a lot!
