### ISSUE TITLE
I don't know how run this

### ISSUE THREAD

**Issue by matheusfelixsm** [smicallef/spiderfoot#1859]
Could not find platform independent libraries <prefix>
Traceback (most recent call last):
  File "C:\Users\Usuário\Downloads\Programs\spiderfoot\sf.py", line 25, in <module>
    import cherrypy
ModuleNotFoundError: No module named 'cherrypy'

Help me with this error

**Comment by donttellmeimcute** [comment]
in the folder run pip install -r requirements.txt

**Comment by MeMyselfAndAI2023** [comment]
Even after full running _pip3 install -r requirements.txt_ there is _cherrypy_ missing (on Windows 10), see:
>python3 ./sf.py -l 127.0.0.1:5001
Traceback (most recent call last):
  File "D:\__AI_Code\spiderfoot-master\sf.py", line 25, in <module>
    import cherrypy
ModuleNotFoundError: No module named 'cherrypy'


How to fix please?


I did everything, reinstalling pip, reinstalling cherrypy (it is there! _python -c "import cherrypy; print(cherrypy.__version__)"
18.9.0_

But still after running 
_python3 ./sf.py -l 127.0.0.1:5001_

I get 


> Traceback (most recent call last):
>   File "D:\__teststuff\spiderfoot-master\sf.py", line 25, in <module>
>     import cherrypy
> ModuleNotFoundError: No module named 'cherrypy'

_

**Comment by MeMyselfAndAI2023** [comment]
> Even after full running _pip3 install -r requirements.txt_ there is _cherrypy_ missing (on Windows 10), see:
> 
> > python3 ./sf.py -l 127.0.0.1:5001
> > Traceback (most recent call last):
> > File "D:__AI_Code\spiderfoot-master\sf.py", line 25, in 
> > import cherrypy
> > ModuleNotFoundError: No module named 'cherrypy'
> 
> How to fix please?
> 
> I did everything, reinstalling pip, reinstalling cherrypy (it is there! _python -c "import cherrypy; print(cherrypy.**version**)" 18.9.0_
> 
> But still after running _python3 ./sf.py -l 127.0.0.1:5001_
> 
> I get
> 
> > Traceback (most recent call last):
> > File "D:__teststuff\spiderfoot-master\sf.py", line 25, in 
> > import cherrypy
> > ModuleNotFoundError: No module named 'cherrypy'
> 
> _

Wait, I found the solution!
Had to type (on Windows10 machine)

> python.exe ./sf.py -l 127.0.0.1:5001

instead of 

> python3 ./sf.py -l 127.0.0.1:5001

to run.
