### ISSUE TITLE
Issue with GUI

### ISSUE THREAD

**Issue by Blipee** [smicallef/spiderfoot#1860]
Hello, use Spiderfoot almost daily, went in today and I am getting this error when I try to launch the GUI: 

python3 ./sf.py -l 127.0.0.1:5001
Traceback (most recent call last):
  File "/home/lana/spiderfoot-4.0/./sf.py", line 31, in <module>
    from sfwebui import SpiderFootWebUi
  File "/home/lana/spiderfoot-4.0/sfwebui.py", line 30, in <module>
    import openpyxl
  File "/usr/local/lib/python3.11/dist-packages/openpyxl/__init__.py", line 9, in <module>
    from openpyxl.workbook import Workbook
  File "/usr/local/lib/python3.11/dist-packages/openpyxl/workbook/__init__.py", line 5, in <module>
    from .workbook import *
  File "/usr/local/lib/python3.11/dist-packages/openpyxl/workbook/workbook.py", line 15, in <module>
    from openpyxl.worksheet import Worksheet
  File "/usr/local/lib/python3.11/dist-packages/openpyxl/worksheet/__init__.py", line 4, in <module>
    from .worksheet import *
  File "/usr/local/lib/python3.11/dist-packages/openpyxl/worksheet/worksheet.py", line 45, in <module>
    from openpyxl.formatting import ConditionalFormatting
  File "/usr/local/lib/python3.11/dist-packages/openpyxl/formatting/__init__.py", line 8, in <module>
    from .rules import CellIsRule, ColorScaleRule, FormatRule, FormulaRule
  File "/usr/local/lib/python3.11/dist-packages/openpyxl/formatting/rules.py", line 5, in <module>
    from collections import Mapping
ImportError: cannot import name 'Mapping' from 'collections' (/usr/lib/python3.11/collections/__init__.py)

**Comment by Blipee** [comment]
When reinstalling and attempting to use again: 

 Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [54 lines of output]
      running egg_info
      writing lib3/PyYAML.egg-info/PKG-INFO
      writing dependency_links to lib3/PyYAML.egg-info/dependency_links.txt
      writing top-level names to lib3/PyYAML.egg-info/top_level.txt
      Traceback (most recent call last):
        File "/usr/lib/python3/dist-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/usr/lib/python3/dist-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/lib/python3/dist-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-w04pnnj8/overlay/local/lib/python3.11/dist-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-w04pnnj8/overlay/local/lib/python3.11/dist-packages/setuptools/build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-w04pnnj8/overlay/local/lib/python3.11/dist-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 271, in <module>
        File "/tmp/pip-build-env-w04pnnj8/overlay/local/lib/python3.11/dist-packages/setuptools/__init__.py", line 104, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-w04pnnj8/overlay/local/lib/python3.11/dist-packages/setuptools/_distutils/core.py", line 184, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-w04pnnj8/overlay/local/lib/python3.11/dist-packages/setuptools/_distutils/core.py", line 200, in run_commands
          dist.run_commands()
        File "/tmp/pip-build-env-w04pnnj8/overlay/local/lib/python3.11/dist-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/tmp/pip-build-env-w04pnnj8/overlay/local/lib/python3.11/dist-packages/setuptools/dist.py", line 967, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-w04pnnj8/overlay/local/lib/python3.11/dist-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-w04pnnj8/overlay/local/lib/python3.11/dist-packages/setuptools/command/egg_info.py", line 321, in run
          self.find_sources()
        File "/tmp/pip-build-env-w04pnnj8/overlay/local/lib/python3.11/dist-packages/setuptools/command/egg_info.py", line 329, in find_sources
          mm.run()
        File "/tmp/pip-build-env-w04pnnj8/overlay/local/lib/python3.11/dist-packages/setuptools/command/egg_info.py", line 550, in run
          self.add_defaults()
        File "/tmp/pip-build-env-w04pnnj8/overlay/local/lib/python3.11/dist-packages/setuptools/command/egg_info.py", line 588, in add_defaults
          sdist.add_defaults(self)
        File "/tmp/pip-build-env-w04pnnj8/overlay/local/lib/python3.11/dist-packages/setuptools/command/sdist.py", line 102, in add_defaults
          super().add_defaults()
        File "/tmp/pip-build-env-w04pnnj8/overlay/local/lib/python3.11/dist-packages/setuptools/_distutils/command/sdist.py", line 250, in add_defaults
          self._add_defaults_ext()
        File "/tmp/pip-build-env-w04pnnj8/overlay/local/lib/python3.11/dist-packages/setuptools/_distutils/command/sdist.py", line 335, in _add_defaults_ext
          self.filelist.extend(build_ext.get_source_files())
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "<string>", line 201, in get_source_files
        File "/tmp/pip-build-env-w04pnnj8/overlay/local/lib/python3.11/dist-packages/setuptools/_distutils/cmd.py", line 107, in __getattr__
          raise AttributeError(attr)
      AttributeError: cython_sources
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by Blipee** [comment]
So the issue appears to be with PyYAML - there is a workaround to fix the issue, which did work for me. For anyone that runs into the same error, you can try this fix here: 

https://github.com/yaml/pyyaml/issues/736

Thanks.
