### ISSUE TITLE
Al ejecutar spiderfoot me aparece el siguiente error. Por favor ayuda!

### ISSUE THREAD

**Issue by Cocind** [smicallef/spiderfoot#1864]
──(kali㉿kali)-[~/spiderfoot]
└─$ spiderfoot -l 127.0.0.0:5001 
Traceback (most recent call last):
  File "/usr/share/spiderfoot/./sf.py", line 29, in <module>
    from sflib import SpiderFoot
  File "/usr/share/spiderfoot/sflib.py", line 34, in <module>
    import dns.resolver
  File "/usr/lib/python3/dist-packages/dns/resolver.py", line 30, in <module>
    import dns._ddr
  File "/usr/lib/python3/dist-packages/dns/_ddr.py", line 12, in <module>
    import dns.nameserver
  File "/usr/lib/python3/dist-packages/dns/nameserver.py", line 5, in <module>
    import dns.asyncquery
  File "/usr/lib/python3/dist-packages/dns/asyncquery.py", line 32, in <module>
    import dns.quic
  File "/usr/lib/python3/dist-packages/dns/quic/__init__.py", line 7, in <module>
    import aioquic.quic.configuration  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/aioquic/quic/configuration.py", line 6, in <module>
    from ..tls import (
  File "/usr/lib/python3/dist-packages/aioquic/tls.py", line 41, in <module>
    from cryptography.hazmat.primitives.asymmetric.types import (
ModuleNotFoundError: No module named 'cryptography.hazmat.primitives.asymmetric.types'

**Comment by bcoles** [comment]
Upgrading `pyOpenSSL`, `pip` and `cryptography` worked for me.

```
pip3 install pip --upgrade
pip3 install pyopenssl --upgrade
pip3 install cryptography --upgrade
```
