### ISSUE TITLE
Scan fail - report as bug/Error 

### ISSUE THREAD

**Issue by kuggaa** [smicallef/spiderfoot#188]
We had a error in a scan.  Upon traveling into the logs I copied the error.  I am in Russia on VPN working out a network in Vegas.  I check network and windows errors but nothing.  Here it is ... have fun.
-------------------------error-------------------log-------------------
2018-06-24 06:18:44 | SpiderFoot | ERROR | Unhandled exception (SystemExit) encountered during scan. Please report this as a bug: ['Traceback (most recent call last):\n', '  File "sfscan.pyc", line 265, in startScan\n', '  File "sflib.pyc", line 1527, in notifyListeners\n', '  File "modules\\sfp_bingsearch.pyc", line 93, in handleEvent\n', '  File "sflib.pyc", line 1527, in notifyListeners\n', '  File "modules\\sfp_spider.pyc", line 262, in handleEvent\n', '  File "modules\\sfp_spider.pyc", line 286, in spiderFrom\n', '  File "modules\\sfp_spider.pyc", line 107, in processUrl\n', '  File "modules\\sfp_spider.pyc", line 199, in contentNotify\n', '  File "sflib.pyc", line 1527, in notifyListeners\n', '  File "modules\\sfp_dnsresolve.pyc", line 162, in handleEvent\n', '  File "modules\\sfp_dnsresolve.pyc", line 334, in processHost\n', '  File "sflib.pyc", line 1527, in notifyListeners\n', '  File "modules\\sfp_bingsearch.pyc", line 93, in handleEvent\n', '  File "sflib.pyc", line 1527, in notifyListeners\n', '  File "modules\\sfp_dnsresolve.pyc", line 162, in handleEvent\n', '  File "modules\\sfp_dnsresolve.pyc", line 338, in processHost\n', '  File "modules\\sfp_dnsresolve.pyc", line 357, in processDomain\n', '  File "sflib.pyc", line 1527, in notifyListeners\n', '  File "modules\\sfp_dnsbrute.pyc", line 131, in handleEvent\n', '  File "sflib.pyc", line 1527, in notifyListeners\n', '  File "modules\\sfp_bingsearch.pyc", line 93, in handleEvent\n', '  File "sflib.pyc", line 1527, in notifyListeners\n', '  File "modules\\sfp_spider.pyc", line 262, in handleEvent\n', '  File "modules\\sfp_spider.pyc", line 286, in spiderFrom\n', '  File "modules\\sfp_spider.pyc", line 135, in processUrl\n', '  File "modules\\sfp_spider.pyc", line 192, in linkNotify\n', '  File "sflib.pyc", line 1527, in notifyListeners\n', '  File "modules\\sfp_crossref.pyc", line 114, in handleEvent\n', '  File "sflib.pyc", line 1054, in fetchUrl\n', '  File "sflib.pyc", line 334, in info\n', '  File "sflib.pyc", line 290, in _dblog\n', '  File "sfdb.pyc", line 339, in scanLogEvent\n', '  File "sflib.pyc", line 306, in fatal\n', 'SystemExit: -1\n']
-- | -- | -- | --

**Comment by mcoumans** [comment]
Similar, I guess.


2018-07-11 17:30:33 | SpiderFoot | ERROR | Unhandled exception (ImportError) encountered during scan. Please report this as a bug: ['Traceback (most recent call last):\n', '  File "/home/mark/Dataschijf/mark/OSINT/Software/spiderfoot/sfscan.py", line 198, in startScan\n    [modName])\n', 'ImportError: No module named sfp_mcafee\n']
-- | -- | -- | --

**Comment by PualCN** [comment]
is this error/bug fixed?

**Comment by smicallef** [comment]
That module has since been deprecated. I guess you are re-running a scan on a newer installation of SpiderFoot, but with a configuration still referencing sfp_mcafee?
