### ISSUE TITLE
'Secure' object has no attribute 'framework

### ISSUE THREAD

**Issue by time2dine** [smicallef/spiderfoot#1891]
I'm trying to run python3.13 on the web ui and keep getting this:
AttributeError: 'Secure' object has no attribute 'framework'

I've tried to install python-framework but that leads me down a rabbit hole that ends in[ ](error: metadata-generation-failed).

Here's more info on the original issue.

Traceback (most recent call last):
  File "/Users/name/spiderfoot/./sf.py", line 634, in <module>
    main()
    ~~~~^^
  File "/Users/name/spiderfoot/./sf.py", line 229, in main
    start_web_server(sfWebUiConfig, sfConfig, loggingQueue)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/name/spiderfoot/./sf.py", line 586, in start_web_server
    cherrypy.quickstart(SpiderFootWebUi(sfWebUiConfig, sfConfig, loggingQueue), script_name=web_root, config=conf)
                        ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/name/spiderfoot/sfwebui.py", line 121, in __init__
    "tools.response_headers.headers": secure_headers.framework.cherrypy()
                                      ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Secure' object has no attribute 'framework'

**Comment by DariuszGulbicki** [comment]
It seems that I have the same issue

**Comment by DariuszGulbicki** [comment]
Ive had the same problem on Arch Linux. Try running the program thru venv. Here is a quick tutorial: https://docs.python.org/3/library/venv.html. In my case the actual commands where shown in terminal. 

![image](https://github.com/user-attachments/assets/400c3833-dcb6-40d4-9874-a416cf09816f)

**Comment by Nebula-0-System** [comment]
hey i tried the venv solution, and i'm still having problems with this not working even through the virtual environment. i set up the venv then used pip3 to install everything. still doesn't work and throws the same error for me. running Linux Mint 22 and Python 3.12.3 on my machine.

any help would be greatly appreciated.

**Comment by Nebula-0-System** [comment]
and update: a hunch i had about the libraries being updated and this project not doing so was correct. looked around for similar errors in other issues and found #1602. python library "secure" needs to be _exactly_ 0.3, use `pip3 install --force-reinstall secure==0.3` to install the correct version. it immediately begins working after doing so

@DariuszGulbicki @time2dine if y'all could test this and lemme know if that fixes it, maintainers can probably close this ticket. either way anyone off google will hopefully find this answer.

**Comment by palWorx** [comment]
"pip3 install --force-reinstall secure==0.3" solved it definitely for me! Thank you!

**Comment by bigsam-666** [comment]
ThanX a lot!

**Comment by tg12** [comment]
That error usually points to running with an unsupported Python version or a mismatched package set in a dirty environment.

The clean fix is to start over in a fresh venv with Python 3.9 or 3.10 and reinstall from `requirements.txt`. Reusing a global or partially-upgraded environment is what usually causes errors like this.

If you need support for a newer interpreter or package combination, please feel free to fork it and submit a PR.
