### ISSUE TITLE
Scan Error

### ISSUE THREAD

**Issue by The-AIGuy** [smicallef/spiderfoot#1903]
2024-11-21 11:49:46 | SpiderFoot | STATUS | Scan [0039FDE0] failed: 'sites'
2024-11-21 11:49:46 | SpiderFoot | ERROR | Unhandled exception (KeyError) encountered during scan. Please report this as a bug: ['Traceback (most recent call last):\n', '  File "sfscan.pyc", line 265, in startScan\n', '  File "sflib.pyc", line 1523, in notifyListeners\n', '  File "modules\\sfp_accounts.pyc", line 230, in handleEvent\n', '  File "modules\\sfp_accounts.pyc", line 162, in batchSites\n', "KeyError: 'sites'\n"]

**Comment by arolen9** [comment]
<html>
<body>
<br><br>
<strong>I got this below. I cannot find any newer discussion threads about this. Can anyone shed light?</strong>
<br><br><br>

2025-05-18 08:00:38 | SpiderFoot | ERROR | Unhandled exception (KeyError) encountered during scan. Please report this as a bug: ['Traceback (most recent call last):\n', '  File "sfscan.pyc", line 265, in startScan\n', '  File "sflib.pyc", line 1523, in notifyListeners\n', '  File "modules\\sfp_dnsresolve.pyc", line 210, in handleEvent\n', '  File "modules\\sfp_dnsresolve.pyc", line 326, in processHost\n', '  File "modules\\sfp_dnsresolve.pyc", line 345, in processDomain\n', '  File "sflib.pyc", line 1523, in notifyListeners\n', '  File "modules\\sfp_accounts.pyc", line 198, in handleEvent\n', '  File "modules\\sfp_accounts.pyc", line 162, in batchSites\n', "KeyError: 'sites'\n"]


</body>
</html>

**Comment by Villa-Buenavista** [comment]
I get this error message and scans stop after a few seconds:

2025-06-13 11:41:31 | SpiderFoot | ERROR | Unhandled exception (KeyError) encountered during scan. Please report this as a bug: ['Traceback (most recent call last):\n', '  File "sfscan.pyc", line 265, in startScan\n', '  File "sflib.pyc", line 1523, in notifyListeners\n', '  File "modules\\sfp_accounts.pyc", line 230, in handleEvent\n', '  File "modules\\sfp_accounts.pyc", line 162, in batchSites\n', "KeyError: 'sites'\n"]

**Comment by swastikpandey09** [comment]
Unhandled exception (KeyError) encountered during scan. Please report this as a bug: ['Traceback (most recent call last):\n', '  File "sfscan.pyc", line 265, in startScan\n', '  File "sflib.pyc", line 1523, in notifyListeners\n', '  File "modules\\sfp_accounts.pyc", line 230, in handleEvent\n', '  File "modules\\sfp_accounts.pyc", line 162, in batchSites\n', "KeyError: 'sites'\n"]
