### ISSUE TITLE
Error Report: "ModuleNotFoundError: No module named 'phonenumbers'

### ISSUE THREAD

**Issue by CyberForensic-stack** [smicallef/spiderfoot#1904]
Please provide a description of the issue and any relevant error messages.
Traceback (most recent call last):
  File "/usr/share/spiderfoot/./sf.py", line 29, in <module>
    from sflib import SpiderFoot
  File "/usr/share/spiderfoot/sflib.py", line 36, in <module>
    import phonenumbers
ModuleNotFoundError: No module named 'phonenumbers' 

What version of Python are you using?
Python3

What version of SpiderFoot are you using (stable release or Git `master` branch)?
4.0-0kali4

* https://github.com/smicallef/spiderfoot/issues

**Comment by XxMrNobodyxX** [comment]
Same problem here. It works fine if you git clone and set up the requirements in a Python virtual environment.
