### ISSUE TITLE
Unhandled exception (BaseException) encountered during scan. Please report this as a bug

### ISSUE THREAD

**Issue by qmarais30** [smicallef/spiderfoot#201]
2018-10-10 22:45:51 | SpiderFoot | ERROR | Unhandled exception (BaseException) encountered during scan. Please report this as a bug: ['Traceback (most recent call last):\n', '  File "sfscan.pyc", line 188, in startScan\n', '  File "sflib.pyc", line 116, in optValueToData\n', '  File "sflib.pyc", line 298, in error\n', 'BaseException: Internal Error Encountered: Unable to open option URL, https://publicsuffix.org/list/effective_tld_names.dat: <urlopen error timed out>\n']
-- | -- | -- | --

**Comment by bcoles** [comment]
Looks like a connection issue. Is `publicsuffix.org` resolvable and routable?
