### ISSUE TITLE
Scan: ERROR_FAILED ('ascii' codec can't encode character u'\ufffd' in position 7)

### ISSUE THREAD

**Issue by nil0x42** [smicallef/spiderfoot#225]
## Issue
Hi, today i tried my first scan with __spiderfoot 2.12__, and it failed due to an `UnicodeEncodeError`.

## __last 2 log entries:__

`2018-11-05 01:58:01	SpiderFoot	STATUS`
```
Scan [2C42551C] failed: 'ascii' codec can't encode character u'\ufffd' in position 7: ordinal not in range(128)
```
------------------------

`2018-11-05 01:58:01	SpiderFoot	ERROR`
```py
Unhandled exception (UnicodeEncodeError) encountered during scan. Please report this as a bug: ['Traceback (most recent call last):
', '  File "/home/alt/sf/sfscan.py", line 265, in startScan
    psMod.notifyListeners(firstEvent)
', '  File "/home/alt/sf/sflib.py", line 1529, in notifyListeners
    listener.handleEvent(sfEvent)
', '  File "/home/alt/sf/modules/sfp_bingsearch.py", line 95, in handleEvent
    self.notifyListeners(evt)
', '  File "/home/alt/sf/sflib.py", line 1529, in notifyListeners
    listener.handleEvent(sfEvent)
', '  File "/home/alt/sf/modules/sfp_spider.py", line 273, in handleEvent
    return self.spiderFrom(spiderTarget)
', '  File "/home/alt/sf/modules/sfp_spider.py", line 297, in spiderFrom
    links = self.processUrl(startingPoint)  # fetch first page
', '  File "/home/alt/sf/modules/sfp_spider.py", line 107, in processUrl
    self.contentNotify(url, fetched, self.urlEvents[url])
', '  File "/home/alt/sf/modules/sfp_spider.py", line 199, in contentNotify
    self.notifyListeners(event)
', '  File "/home/alt/sf/sflib.py", line 1529, in notifyListeners
    listener.handleEvent(sfEvent)
', '  File "/home/alt/sf/modules/sfp_dnsresolve.py", line 171, in handleEvent
    self.processHost(match[1], parentEvent, False)
', '  File "/home/alt/sf/modules/sfp_dnsresolve.py", line 350, in processHost
    self.notifyListeners(evt)
', '  File "/home/alt/sf/sflib.py", line 1529, in notifyListeners
    listener.handleEvent(sfEvent)
', '  File "/home/alt/sf/modules/sfp_bingsearch.py", line 95, in handleEvent
    self.notifyListeners(evt)
', '  File "/home/alt/sf/sflib.py", line 1529, in notifyListeners
    listener.handleEvent(sfEvent)
', '  File "/home/alt/sf/modules/sfp_spider.py", line 273, in handleEvent
    return self.spiderFrom(spiderTarget)
', '  File "/home/alt/sf/modules/sfp_spider.py", line 297, in spiderFrom
    links = self.processUrl(startingPoint)  # fetch first page
', '  File "/home/alt/sf/modules/sfp_spider.py", line 107, in processUrl
    self.contentNotify(url, fetched, self.urlEvents[url])
', '  File "/home/alt/sf/modules/sfp_spider.py", line 199, in contentNotify
    self.notifyListeners(event)
', '  File "/home/alt/sf/sflib.py", line 1529, in notifyListeners
    listener.handleEvent(sfEvent)
', '  File "/home/alt/sf/modules/sfp_dnsresolve.py", line 171, in handleEvent
    self.processHost(match[1], parentEvent, False)
', '  File "/home/alt/sf/modules/sfp_dnsresolve.py", line 354, in processHost
    self.processDomain(dom, evt)
', '  File "/home/alt/sf/modules/sfp_dnsresolve.py", line 373, in processDomain
    self.notifyListeners(domevt)
', '  File "/home/alt/sf/sflib.py", line 1529, in notifyListeners
    listener.handleEvent(sfEvent)
', '  File "/home/alt/sf/modules/sfp_builtwith.py", line 137, in handleEvent
    self.notifyListeners(ev)
', '  File "/home/alt/sf/sflib.py", line 1529, in notifyListeners
    listener.handleEvent(sfEvent)
', '  File "/home/alt/sf/modules/sfp_virustotal.py", line 224, in handleEvent
    self.notifyListeners(e)
', '  File "/home/alt/sf/sflib.py", line 1529, in notifyListeners
    listener.handleEvent(sfEvent)
', '  File "/home/alt/sf/modules/sfp_bingsearch.py", line 101, in handleEvent
    self.notifyListeners(evt)
', '  File "/home/alt/sf/sflib.py", line 1529, in notifyListeners
    listener.handleEvent(sfEvent)
', '  File "/home/alt/sf/modules/sfp_dnsresolve.py", line 171, in handleEvent
    self.processHost(match[1], parentEvent, False)
', '  File "/home/alt/sf/modules/sfp_dnsresolve.py", line 350, in processHost
    self.notifyListeners(evt)
', '  File "/home/alt/sf/sflib.py", line 1529, in notifyListeners
    listener.handleEvent(sfEvent)
', '  File "/home/alt/sf/modules/sfp_bingsearch.py", line 95, in handleEvent
    self.notifyListeners(evt)
', '  File "/home/alt/sf/sflib.py", line 1529, in notifyListeners
    listener.handleEvent(sfEvent)
', '  File "/home/alt/sf/modules/sfp_spider.py", line 273, in handleEvent
    return self.spiderFrom(spiderTarget)
', '  File "/home/alt/sf/modules/sfp_spider.py", line 297, in spiderFrom
    links = self.processUrl(startingPoint)  # fetch first page
', '  File "/home/alt/sf/modules/sfp_spider.py", line 107, in processUrl
    self.contentNotify(url, fetched, self.urlEvents[url])
', '  File "/home/alt/sf/modules/sfp_spider.py", line 199, in contentNotify
    self.notifyListeners(event)
', '  File "/home/alt/sf/sflib.py", line 1529, in notifyListeners
    listener.handleEvent(sfEvent)
', '  File "/home/alt/sf/modules/sfp_dnsresolve.py", line 171, in handleEvent
    self.processHost(match[1], parentEvent, False)
', '  File "/home/alt/sf/modules/sfp_dnsresolve.py", line 350, in processHost
    self.notifyListeners(evt)
', '  File "/home/alt/sf/sflib.py", line 1529, in notifyListeners
    listener.handleEvent(sfEvent)
', '  File "/home/alt/sf/modules/sfp_bingsearch.py", line 95, in handleEvent
    self.notifyListeners(evt)
', '  File "/home/alt/sf/sflib.py", line 1529, in notifyListeners
    listener.handleEvent(sfEvent)
', '  File "/home/alt/sf/modules/sfp_spider.py", line 273, in handleEvent
    return self.spiderFrom(spiderTarget)
', '  File "/home/alt/sf/modules/sfp_spider.py", line 297, in spiderFrom
    links = self.processUrl(startingPoint)  # fetch first page
', '  File "/home/alt/sf/modules/sfp_spider.py", line 107, in processUrl
    self.contentNotify(url, fetched, self.urlEvents[url])
', '  File "/home/alt/sf/modules/sfp_spider.py", line 199, in contentNotify
    self.notifyListeners(event)
', '  File "/home/alt/sf/sflib.py", line 1529, in notifyListeners
    listener.handleEvent(sfEvent)
', '  File "/home/alt/sf/modules/sfp_dnsresolve.py", line 171, in handleEvent
    self.processHost(match[1], parentEvent, False)
', '  File "/home/alt/sf/modules/sfp_dnsresolve.py", line 350, in processHost
    self.notifyListeners(evt)
', '  File "/home/alt/sf/sflib.py", line 1529, in notifyListeners
    listener.handleEvent(sfEvent)
', '  File "/home/alt/sf/modules/sfp_bingsearch.py", line 95, in handleEvent
    self.notifyListeners(evt)
', '  File "/home/alt/sf/sflib.py", line 1529, in notifyListeners
    listener.handleEvent(sfEvent)
', '  File "/home/alt/sf/modules/sfp_spider.py", line 273, in handleEvent
    return self.spiderFrom(spiderTarget)
', '  File "/home/alt/sf/modules/sfp_spider.py", line 297, in spiderFrom
    links = self.processUrl(startingPoint)  # fetch first page
', '  File "/home/alt/sf/modules/sfp_spider.py", line 107, in processUrl
    self.contentNotify(url, fetched, self.urlEvents[url])
', '  File "/home/alt/sf/modules/sfp_spider.py", line 199, in contentNotify
    self.notifyListeners(event)
', '  File "/home/alt/sf/sflib.py", line 1529, in notifyListeners
    listener.handleEvent(sfEvent)
', '  File "/home/alt/sf/modules/sfp_dnsresolve.py", line 171, in handleEvent
    self.processHost(match[1], parentEvent, False)
', '  File "/home/alt/sf/modules/sfp_dnsresolve.py", line 350, in processHost
    self.notifyListeners(evt)
', '  File "/home/alt/sf/sflib.py", line 1529, in notifyListeners
    listener.handleEvent(sfEvent)
', '  File "/home/alt/sf/modules/sfp_mnemonic.py", line 169, in handleEvent
    self.notifyListeners(evt)
', '  File "/home/alt/sf/sflib.py", line 1529, in notifyListeners
    listener.handleEvent(sfEvent)
', '  File "/home/alt/sf/modules/sfp_bingsharedip.py", line 140, in handleEvent
    self.notifyListeners(evt)
', '  File "/home/alt/sf/sflib.py", line 1529, in notifyListeners
    listener.handleEvent(sfEvent)
', '  File "/home/alt/sf/modules/sfp_dnsresolve.py", line 171, in handleEvent
    self.processHost(match[1], parentEvent, False)
', '  File "/home/alt/sf/modules/sfp_dnsresolve.py", line 350, in processHost
    self.notifyListeners(evt)
', '  File "/home/alt/sf/sflib.py", line 1529, in notifyListeners
    listener.handleEvent(sfEvent)
', '  File "/home/alt/sf/modules/sfp_mnemonic.py", line 169, in handleEvent
    self.notifyListeners(evt)
', '  File "/home/alt/sf/sflib.py", line 1529, in notifyListeners
    listener.handleEvent(sfEvent)
', '  File "/home/alt/sf/modules/sfp_bingsharedip.py", line 140, in handleEvent
    self.notifyListeners(evt)
', '  File "/home/alt/sf/sflib.py", line 1529, in notifyListeners
    listener.handleEvent(sfEvent)
', '  File "/home/alt/sf/modules/sfp_dnsresolve.py", line 171, in handleEvent
    self.processHost(match[1], parentEvent, False)
', '  File "/home/alt/sf/modules/sfp_dnsresolve.py", line 350, in processHost
    self.notifyListeners(evt)
', '  File "/home/alt/sf/sflib.py", line 1529, in notifyListeners
    listener.handleEvent(sfEvent)
', '  File "/home/alt/sf/modules/sfp_virustotal.py", line 224, in handleEvent
    self.notifyListeners(e)
', '  File "/home/alt/sf/sflib.py", line 1529, in notifyListeners
    listener.handleEvent(sfEvent)
', '  File "/home/alt/sf/modules/sfp_bingsearch.py", line 95, in handleEvent
    self.notifyListeners(evt)
', '  File "/home/alt/sf/sflib.py", line 1529, in notifyListeners
    listener.handleEvent(sfEvent)
', '  File "/home/alt/sf/modules/sfp_spider.py", line 273, in handleEvent
    return self.spiderFrom(spiderTarget)
', '  File "/home/alt/sf/modules/sfp_spider.py", line 297, in spiderFrom
    links = self.processUrl(startingPoint)  # fetch first page
', '  File "/home/alt/sf/modules/sfp_spider.py", line 107, in processUrl
    self.contentNotify(url, fetched, self.urlEvents[url])
', '  File "/home/alt/sf/modules/sfp_spider.py", line 199, in contentNotify
    self.notifyListeners(event)
', '  File "/home/alt/sf/sflib.py", line 1529, in notifyListeners
    listener.handleEvent(sfEvent)
', '  File "/home/alt/sf/modules/sfp_company.py", line 172, in handleEvent
    self.notifyListeners(evt)
', '  File "/home/alt/sf/sflib.py", line 1529, in notifyListeners
    listener.handleEvent(sfEvent)
', '  File "/home/alt/sf/modules/sfp_opencorporates.py", line 178, in handleEvent
    res = self.searchCompany(eventData + "*")
', '  File "/home/alt/sf/modules/sfp_opencorporates.py", line 66, in searchCompany
    res = self.sf.fetchUrl("https://api.opencorporates.com/v0.4/companies/search?" + urllib.urlencode(params),
', '  File "/usr/lib/python2.7/urllib.py", line 1342, in urlencode
    v = quote_plus(str(v))
', "UnicodeEncodeError: 'ascii' codec can't encode character u'\\ufffd' in position 7: ordinal not in range(128)
"]
```

**Comment by nil0x42** [comment]
I saw a lot of similar issues here and don;t you think it will be a good option to not crash a full scan on a simple module bug ?
Some `try ... except BaseException` with correct error reporting on handleEvent() will probably improve resilience to bugs, while still reporting bugs and being able to fix them.

**Comment by smicallef** [comment]
Thanks for reporting this. Clearly a bug and I'll take a look. On not failing on errors, the issue is that it can lead to misleading results. I would prefer to have a highly robust module base that handles errors well (clearly this doesn't, as various others also do not), but I think it's dangerous to say that a scan completed and yet modules failed.

What I'd prefer is a way to side-step the error, report it in the UI to indicate to the user that some data may be missing, and continue. But that's a bigger change which I haven't had time for so far, and am therefore resting on the mindset above :)

**Comment by nil0x42** [comment]
Yes, i understand.
But modules are never as robust as we d'like (especially for online OSINT API callers, that tend to need regular updates).

And having a 4 days scan interrupted because of a single module failure is really trustrating.

But i understand that continuing the scan would be an incentive for users to not report bugs. So instead maybe it's a good idea to continue the scan, still marking it as "INCOMPLETE SCAN: BUGS FOUND PLEASE REPORT", so users still report, while enjoying the full results of the modules that didn't failed.

**Comment by smicallef** [comment]
Yes, valid points indeed. Let me think about how to do this properly.

**Comment by smicallef** [comment]
OK, I've pushed a number of changes to a) Handle Unicode as a target and in results, b) To better handle cases of external data being broken/missing and c) Not fail the scan when errors are encountered. I will introduce a configuration open to control it, for those who do want to fail on errors though.

**Comment by nil0x42** [comment]
Thank you ! i'll try the version with patch right now, and of course i'll continue reporting any bug i find :)
