### ISSUE TITLE
Unhandled exception (TypeError) encountered during scan. Please report this as a bug

### ISSUE THREAD

**Issue by nil0x42** [smicallef/spiderfoot#226]
# Issue
`Unhandled exception (TypeError) encountered during scan. Please report this as a bug`
```py
Traceback (most recent call last):
  File "/home/user/tools/spiderfoot/sfscan.py", line 265, in startScan
    psMod.notifyListeners(firstEvent)
  File "/home/user/tools/spiderfoot/sflib.py", line 1529, in notifyListeners
    listener.handleEvent(sfEvent)
  File "/home/user/tools/spiderfoot/modules/sfp_bingsearch.py", line 95, in handleEvent
    self.notifyListeners(evt)
  File "/home/user/tools/spiderfoot/sflib.py", line 1529, in notifyListeners
    listener.handleEvent(sfEvent)
  File "/home/user/tools/spiderfoot/modules/sfp_spider.py", line 273, in handleEvent
    return self.spiderFrom(spiderTarget)
  File "/home/user/tools/spiderfoot/modules/sfp_spider.py", line 297, in spiderFrom
    links = self.processUrl(startingPoint)  # fetch first page
  File "/home/user/tools/spiderfoot/modules/sfp_spider.py", line 107, in processUrl
    self.contentNotify(url, fetched, self.urlEvents[url])
  File "/home/user/tools/spiderfoot/modules/sfp_spider.py", line 199, in contentNotify
    self.notifyListeners(event)
  File "/home/user/tools/spiderfoot/sflib.py", line 1529, in notifyListeners
    listener.handleEvent(sfEvent)
  File "/home/user/tools/spiderfoot/modules/sfp_dnsresolve.py", line 171, in handleEvent
    self.processHost(match[1], parentEvent, False)
  File "/home/user/tools/spiderfoot/modules/sfp_dnsresolve.py", line 350, in processHost
    self.notifyListeners(evt)
  File "/home/user/tools/spiderfoot/sflib.py", line 1529, in notifyListeners
    listener.handleEvent(sfEvent)
  File "/home/user/tools/spiderfoot/modules/sfp_commoncrawl.py", line 118, in handleEvent
    self.indexBase = self.getLatestIndexes()
  File "/home/user/tools/spiderfoot/modules/sfp_commoncrawl.py", line 74, in getLatestIndexes
    indexes = re.findall(".*(CC-MAIN-\\d+-\\d+).*", res[\'content\'])
  File "/usr/lib/python2.7/re.py", line 181, in findall
    return _compile(pattern, flags).findall(string)
TypeError: expected string or buffer
```

**Comment by smicallef** [comment]
Just pushed a fix. Please pull and verify.
