### ISSUE TITLE
Unhandled exception (TypeError) encountered during scan. Please report this as a bug

### ISSUE THREAD

**Issue by nil0x42** [smicallef/spiderfoot#227]
git describe: `v2.11.0-final-202-gc1def64`

`Unhandled exception (TypeError) encountered during scan. Please report this as a bug`
```py
Traceback (most recent call last):
  File "/home/user/tools/spiderfoot/sfscan.py", line 265, in startScan
    psMod.notifyListeners(firstEvent)
  File "/home/user/tools/spiderfoot/sflib.py", line 1529, in notifyListeners
    listener.handleEvent(sfEvent)
  File "/home/user/tools/spiderfoot/modules/sfp_commoncrawl.py", line 130, in handleEvent
    if len(self.indexBase) == 0:
TypeError: object of type 'NoneType' has no len()
```

**Comment by smicallef** [comment]
Fix just pushed.
