### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by bomboem** [smicallef/spiderfoot#235]
When I enter  a project name and a project mail address; this appears:

```
500 Internal Server Error
The server encountered an unexpected condition which prevented it from fulfilling the request.

Traceback (most recent call last):
  File "cherrypy\_cprequest.pyc", line 656, in respond
  File "cherrypy\lib\encoding.pyc", line 188, in __call__
  File "cherrypy\_cpdispatch.pyc", line 34, in __call__
  File "sfwebui.pyc", line 698, in startscan
  File "sflib.pyc", line 285, in genScanInstanceGUID
UnicodeEncodeError: 'ascii' codec can't encode character u'\xeb' in position 9: ordinal not in range(128)
```

**Comment by ALeeson-dev-Mjolnir** [comment]
This issue is still not fixed in the v2 API when trying to grab scan correlations (https://sf-j544wwda.hx.spiderfoot.net/api/v2/scans/{scan_id}/correlations)
