### ISSUE TITLE
The Authorization header could not be parsed.

### ISSUE THREAD

**Issue by Paulpatou** [smicallef/spiderfoot#262]
Hi
I have this error after restarting docker.
Do you have any ideas?
```

400 Bad Request

The Authorization header could not be parsed.

Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/cherrypy/_cprequest.py", line 667, in respond
    self.hooks.run('before_handler')
  File "/usr/lib/python2.7/site-packages/cherrypy/_cprequest.py", line 114, in run
    raise exc
HTTPError: (400, 'The Authorization header could not be parsed.')

```

**Comment by bcoles** [comment]
This happens when your browser is sending empty credentials in the `Authorization` header.

If you aren't prompted for credentials, it is likely that you've attempted to authenticate with blank credentials, which your browser has cached. Clearing your cache should resolve the issue.

This is a bug and should be fixed.

The error can be reproduced with the following command:

```
curl -isk http://127.0.0.1:5001/ -H 'Authorization: Digest username="", realm="' 
```
