### ISSUE TITLE
Unrecoverable error in the server.

### ISSUE THREAD

**Issue by Singnusit** [smicallef/spiderfoot#465]
Hi,

First of all, thank you for this tool and for the answer to my previous request.

Then here's the error I encounter when I launch spiderfoot in WebUI.
What's causing it ?

Thank you for your response

Sincerely

OS : windows 10 18362.592
Browser : Firefox 72.0.2
---
Traceback (most recent call last):
  File "C:\Users\Test\AppData\Local\Programs\Python\Python38\lib\site-packages\cherrypy\_cprequest.py", line 638, in respond
    self._do_respond(path_info)
  File "C:\Users\Test\AppData\Local\Programs\Python\Python38\lib\site-packages\cherrypy\_cprequest.py", line 697, in _do_respond
    response.body = self.handler()
  File "C:\Users\Test\AppData\Local\Programs\Python\Python38\lib\site-packages\cherrypy\lib\encoding.py", line 219, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "C:\Users\Test\AppData\Local\Programs\Python\Python38\lib\site-packages\cherrypy\_cpdispatch.py", line 54, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "C:\Users\Test\spiderfoot\sfwebui.py", line 469, in scaninfo
    return templ.render(id=id, name=cgi.escape(res[0]), status=res[5], docroot=self.docroot,
AttributeError: module 'cgi' has no attribute 'escape'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Test\AppData\Local\Programs\Python\Python38\lib\site-packages\cherrypy\_cprequest.py", line 604, in run
    self.respond(pi)
  File "C:\Users\Test\AppData\Local\Programs\Python\Python38\lib\site-packages\cherrypy\_cprequest.py", line 653, in respond
    self.handle_error()
  File "C:\Users\Test\AppData\Local\Programs\Python\Python38\lib\site-packages\cherrypy\_cprequest.py", line 766, in handle_error
    self.error_response()
  File "C:\Users\Test\spiderfoot\sfwebui.py", line 80, in error_page
    cherrypy.response.body = '<html><body>Error</body></html>'
  File "C:\Users\Test\AppData\Local\Programs\Python\Python38\lib\site-packages\cherrypy\__init__.py", line 231, in __setattr__
    setattr(child, name, value)
  File "C:\Users\Test\AppData\Local\Programs\Python\Python38\lib\site-packages\cherrypy\_cprequest.py", line 792, in __set__
    raise ValueError(self.unicode_err)
ValueError: Page handlers MUST return bytes. Use tools.encode if you wish to return unicode.

**Comment by lupa18** [comment]
Same here. My log: 

```
Unrecoverable error in the server.
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/cherrypy/_cprequest.py", line 638, in respond
    self._do_respond(path_info)
  File "/usr/lib/python3.8/site-packages/cherrypy/_cprequest.py", line 697, in _do_respond
    response.body = self.handler()
  File "/usr/lib/python3.8/site-packages/cherrypy/lib/encoding.py", line 219, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/cherrypy/_cpdispatch.py", line 54, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/home/spiderfoot/sfwebui.py", line 759, in startscan
    [scanname, scantarget] = self.cleanUserInput([scanname, scantarget])
  File "/home/spiderfoot/sfwebui.py", line 91, in cleanUserInput
    c = cgi.escape(item, True)
AttributeError: module 'cgi' has no attribute 'escape'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/cherrypy/_cprequest.py", line 604, in run
    self.respond(pi)
  File "/usr/lib/python3.8/site-packages/cherrypy/_cprequest.py", line 653, in respond
    self.handle_error()
  File "/usr/lib/python3.8/site-packages/cherrypy/_cprequest.py", line 766, in handle_error
    self.error_response()
  File "/home/spiderfoot/sfwebui.py", line 80, in error_page
    cherrypy.response.body = '<html><body>Error</body></html>'
  File "/usr/lib/python3.8/site-packages/cherrypy/__init__.py", line 231, in __setattr__
    setattr(child, name, value)
  File "/usr/lib/python3.8/site-packages/cherrypy/_cprequest.py", line 792, in __set__
    raise ValueError(self.unicode_err)
ValueError: Page handlers MUST return bytes. Use tools.encode if you wish to return unicode.

```

**Comment by arandomvisitorhere** [comment]
Same issue here too.. :(

**Comment by smicallef** [comment]
Looks like Python 3.8 removed cgi.escape. I'll push a fix shortly.

**Comment by smicallef** [comment]
Fixed pushed, let me know if you experience any other issues since I haven't tested with Python 3.8.

**Comment by Singnusit** [comment]
Hi,

Thank you for your work. Here's another mistake

Sincerely
---
Unhandled exception (UnicodeEncodeError) encountered during scan. Please report this as a bug: ['Traceback (most recent call last):\n', '  File "C:\\Users\\Test\\spiderfoot\\sfscan.py", line 151, in startScan\n    self.ts.sf.cachePut("internet_tlds", self.ts.config[\'_internettlds\'])\n', '  File "C:\\Users\\Test\\spiderfoot\\sflib.py", line 433, in cachePut\n    fp.write(line.decode(\'utf-8\') + \'\\n\')\n', '  File "C:\\Users\\Test\\AppData\\Local\\Programs\\Python\\Python38\\lib\\encodings\\cp1252.py", line 19, in encode\n    return codecs.charmap_encode(input,self.errors,encoding_table)[0]\n', "UnicodeEncodeError: 'charmap' codec can't encode characters in position 0-1: character maps to <undefined>\n"]

**Comment by smicallef** [comment]
Are you able to try a 3.6 or 3.7 version of Python to see if this still happens? What exact version of Python 3.8 are you using - 3.8 or 3.8.1?

**Comment by Singnusit** [comment]
i'm using python 3.8 and git 4.4.23(1)-release (x86_64-pc-msys)
I'll try with version 3.6
