### ISSUE TITLE
install problem

### ISSUE THREAD

**Issue by shanow7** [smicallef/spiderfoot#476]

**Comment by bcoles** [comment]
Python3 is required.

```
python3 sf.py
```

**Comment by jfqd** [comment]
On macOS i get:

```
$ brew install python3
$ pip3 install -r requirements.txt
$ python3 sf.py
Traceback (most recent call last):
  File "sf.py", line 24, in <module>
    from sflib import SpiderFoot
  File "/Users/jerry/Desktop/spiderfoot/sflib.py", line 35, in <module>
    import dns.resolver
  File "/usr/local/lib/python3.7/site-packages/dns/resolver.py", line 34, in <module>
    import dns.message
  File "/usr/local/lib/python3.7/site-packages/dns/message.py", line 30, in <module>
    import dns.opcode
ModuleNotFoundError: No module named 'dns.opcode'
```

Any ideas?

**Comment by Tejaswgupta** [comment]
try `pip3 install dnspython`

**Comment by jfqd** [comment]
Thx for your suggestion, but it does not fix it, cause dnspython is still installed:

```
Requirement already satisfied: dnspython in /usr/local/lib/python3.7/site-packages (1.16.0)
```

**Comment by Tejaswgupta** [comment]
Try fresh install:
`rm -rf your-current-installation`
`git clone https://github.com/smicallef/spiderfoot.git`
`python3 install -r requirement.txt`
`python3 install sf.py`

**Comment by jfqd** [comment]
You mean:

```
git clone https://github.com/smicallef/spiderfoot.git
cd spiderfoot
pip3 install -r requirements.txt
python3 sf.py
```

which outputs the same als above:

```
Traceback (most recent call last):
  File "sf.py", line 24, in <module>
    from sflib import SpiderFoot
  File "/Users/jerry/Desktop/spiderfoot/sflib.py", line 35, in <module>
    import dns.resolver
  File "/usr/local/lib/python3.7/site-packages/dns/resolver.py", line 34, in <module>
    import dns.message
  File "/usr/local/lib/python3.7/site-packages/dns/message.py", line 30, in <module>
    import dns.opcode
ModuleNotFoundError: No module named 'dns.opcode'
```

**Comment by noon-jpg** [comment]
you don't have permissions to open it chk ur system, what ever the line 35 or 10

**Comment by kernelr00ter** [comment]
apt update -y
apt install -y python3-pip
pip3 install --upgrade setuptools
git clone https://github.com/smicallef/spiderfoot && cd spiderfoot && pip3 install -r requirements.txt
