### ISSUE TITLE
Requirements Failure at Line 19

### ISSUE THREAD

**Issue by shink3n** [smicallef/spiderfoot#492]
ERROR: Could not find a version that satisfies the requirement secure (from -r requirements.txt (line 19)) (from versions: none)
ERROR: No matching distribution found for secure (from -r requirements.txt (line 19))

Same appears in python2.7 and 3

**Comment by bcoles** [comment]
> Same appears in python2.7 and 3

Are you sure you're using the correct version of `pip` for Python3, ie `pip3` ? The `secure` dependency requires Python 3.

```
> pip3 install -r requirements.txt 
Gkr-Message: 00:13:01.161: secret service operation failed: The name org.freedesktop.secrets was not provided by any .service files
Requirement already satisfied: adblockparser>=0.7 in /usr/local/lib/python3.7/dist-packages (from -r requirements.txt (line 1)) (0.7)
Requirement already satisfied: dnspython>=1.16.0 in /usr/lib/python3/dist-packages (from -r requirements.txt (line 2)) (1.16.0)
Requirement already satisfied: exifread>=2.1.2 in /usr/local/lib/python3.7/dist-packages (from -r requirements.txt (line 3)) (2.1.2)
Requirement already satisfied: CherryPy>=14.0.0 in /usr/local/lib/python3.7/dist-packages (from -r requirements.txt (line 4)) (18.3.0)
Requirement already satisfied: Mako>=1.0.4 in /usr/lib/python3/dist-packages (from -r requirements.txt (line 5)) (1.0.7)
Requirement already satisfied: beautifulsoup4>=4.4.1 in /usr/local/lib/python3.7/dist-packages (from -r requirements.txt (line 6)) (4.6.3)
Requirement already satisfied: lxml>=3.4.4 in /usr/lib/python3/dist-packages (from -r requirements.txt (line 7)) (4.4.2)
Requirement already satisfied: netaddr>=0.7.18 in /usr/local/lib/python3.7/dist-packages (from -r requirements.txt (line 8)) (0.7.19)
Requirement already satisfied: pysocks>=1.7.1 in /usr/local/lib/python3.7/dist-packages (from -r requirements.txt (line 9)) (1.7.1)
Requirement already satisfied: requests>=2.20.0 in /usr/local/lib/python3.7/dist-packages (from -r requirements.txt (line 10)) (2.21.0)
Requirement already satisfied: ipwhois==1.0.0 in /usr/local/lib/python3.7/dist-packages (from -r requirements.txt (line 11)) (1.0.0)
Requirement already satisfied: ipaddr>=2.2.0 in /usr/local/lib/python3.7/dist-packages (from -r requirements.txt (line 12)) (2.2.0)
Requirement already satisfied: phonenumbers>=8.10.2 in /usr/local/lib/python3.7/dist-packages (from -r requirements.txt (line 13)) (8.10.2)
Requirement already satisfied: pygexf>=0.2.2 in /usr/local/lib/python3.7/dist-packages (from -r requirements.txt (line 14)) (0.2.2)
Requirement already satisfied: PyPDF2>=1.26.0 in /usr/local/lib/python3.7/dist-packages (from -r requirements.txt (line 15)) (1.26.0)
Requirement already satisfied: stem>=1.7.1 in /usr/local/lib/python3.7/dist-packages (from -r requirements.txt (line 16)) (1.7.1)
Requirement already satisfied: python-whois>=0.7.1 in /usr/local/lib/python3.7/dist-packages (from -r requirements.txt (line 17)) (0.7.2)
Requirement already satisfied: future in /usr/lib/python3/dist-packages (from -r requirements.txt (line 18)) (0.18.2)
Requirement already satisfied: secure in /usr/local/lib/python3.7/dist-packages (from -r requirements.txt (line 19)) (0.2.1)
Requirement already satisfied: pyOpenSSL>=16.2.0 in /usr/lib/python3/dist-packages (from -r requirements.txt (line 20)) (19.0.0)
Requirement already satisfied: python-docx>=0.8.10 in /usr/local/lib/python3.7/dist-packages (from -r requirements.txt (line 21)) (0.8.10)
Requirement already satisfied: python-pptx>=0.6.18 in /usr/local/lib/python3.7/dist-packages (from -r requirements.txt (line 22)) (0.6.18)
Requirement already satisfied: networkx==2.3 in /usr/local/lib/python3.7/dist-packages (from -r requirements.txt (line 23)) (2.3)
Requirement already satisfied: cryptography>=2.5 in /usr/local/lib/python3.7/dist-packages (from -r requirements.txt (line 24)) (2.8)
Requirement already satisfied: zc.lockfile in /usr/local/lib/python3.7/dist-packages (from CherryPy>=14.0.0->-r requirements.txt (line 4)) (2.0)
Requirement already satisfied: portend>=2.1.1 in /usr/local/lib/python3.7/dist-packages (from CherryPy>=14.0.0->-r requirements.txt (line 4)) (2.5)
Requirement already satisfied: cheroot>=6.2.4 in /usr/local/lib/python3.7/dist-packages (from CherryPy>=14.0.0->-r requirements.txt (line 4)) (8.2.1)
Requirement already satisfied: more-itertools in /usr/local/lib/python3.7/dist-packages (from CherryPy>=14.0.0->-r requirements.txt (line 4)) (7.2.0)
Requirement already satisfied: idna<2.9,>=2.5 in /usr/lib/python3/dist-packages (from requests>=2.20.0->-r requirements.txt (line 10)) (2.6)
Requirement already satisfied: urllib3<1.25,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests>=2.20.0->-r requirements.txt (line 10)) (1.24.2)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/lib/python3/dist-packages (from requests>=2.20.0->-r requirements.txt (line 10)) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in /usr/lib/python3/dist-packages (from requests>=2.20.0->-r requirements.txt (line 10)) (2019.11.28)
Requirement already satisfied: XlsxWriter>=0.5.7 in /usr/lib/python3/dist-packages (from python-pptx>=0.6.18->-r requirements.txt (line 22)) (1.1.2)
Requirement already satisfied: Pillow>=3.3.2 in /usr/lib/python3/dist-packages (from python-pptx>=0.6.18->-r requirements.txt (line 22)) (6.2.1)
Requirement already satisfied: decorator>=4.3.0 in /usr/lib/python3/dist-packages (from networkx==2.3->-r requirements.txt (line 23)) (4.3.0)
Requirement already satisfied: cffi!=1.11.3,>=1.8 in /usr/local/lib/python3.7/dist-packages (from cryptography>=2.5->-r requirements.txt (line 24)) (1.13.0)
Requirement already satisfied: six>=1.4.1 in /usr/lib/python3/dist-packages (from cryptography>=2.5->-r requirements.txt (line 24)) (1.14.0)
Requirement already satisfied: setuptools in /usr/lib/python3/dist-packages (from zc.lockfile->CherryPy>=14.0.0->-r requirements.txt (line 4)) (44.0.0)
Requirement already satisfied: tempora>=1.8 in /usr/local/lib/python3.7/dist-packages (from portend>=2.1.1->CherryPy>=14.0.0->-r requirements.txt (line 4)) (1.14.1)
Requirement already satisfied: jaraco.functools in /usr/local/lib/python3.7/dist-packages (from cheroot>=6.2.4->CherryPy>=14.0.0->-r requirements.txt (line 4)) (2.0)
Requirement already satisfied: pycparser in /usr/local/lib/python3.7/dist-packages (from cffi!=1.11.3,>=1.8->cryptography>=2.5->-r requirements.txt (line 24)) (2.19)
Requirement already satisfied: pytz in /usr/local/lib/python3.7/dist-packages (from tempora>=1.8->portend>=2.1.1->CherryPy>=14.0.0->-r requirements.txt (line 4)) (2019.1)
WARNING: You are using pip version 19.3.1; however, version 20.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

**Comment by bcoles** [comment]
I was able to reproduce your issue, but only with `pip2` :

```
> pip2 install -r requirements.txt  
Gkr-Message: 00:14:35.035: secret service operation failed: The name org.freedesktop.secrets was not provided by any .service files
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Requirement already satisfied: adblockparser>=0.7 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 1)) (0.7)
Requirement already satisfied: dnspython>=1.16.0 in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 2)) (1.16.0)
Requirement already satisfied: exifread>=2.1.2 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 3)) (2.1.2)
Requirement already satisfied: CherryPy>=14.0.0 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 4)) (17.4.2)
Requirement already satisfied: Mako>=1.0.4 in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 5)) (1.0.7)
Requirement already satisfied: beautifulsoup4>=4.4.1 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 6)) (4.6.3)
Requirement already satisfied: lxml>=3.4.4 in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 7)) (4.4.2)
Requirement already satisfied: netaddr>=0.7.18 in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 8)) (0.7.19)
Collecting pysocks>=1.7.1
  Using cached https://files.pythonhosted.org/packages/a2/4b/52123768624ae28d84c97515dd96c9958888e8c2d8f122074e31e2be878c/PySocks-1.7.1-py27-none-any.whl
Requirement already satisfied: requests>=2.20.0 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 10)) (2.21.0)
Requirement already satisfied: ipwhois==1.0.0 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 11)) (1.0.0)
Requirement already satisfied: ipaddr>=2.2.0 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 12)) (2.2.0)
Requirement already satisfied: phonenumbers>=8.10.2 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 13)) (8.10.2)
Requirement already satisfied: pygexf>=0.2.2 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 14)) (0.2.2)
Requirement already satisfied: PyPDF2>=1.26.0 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 15)) (1.26.0)
Requirement already satisfied: stem>=1.7.1 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 16)) (1.7.1)
Requirement already satisfied: python-whois>=0.7.1 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 17)) (0.7.1)
Requirement already satisfied: future in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 18)) (0.16.0)
ERROR: Could not find a version that satisfies the requirement secure (from -r requirements.txt (line 19)) (from versions: none)
ERROR: No matching distribution found for secure (from -r requirements.txt (line 19))
WARNING: You are using pip version 19.3.1; however, version 20.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

**Comment by t3chn0m4g3** [comment]
@bcoles I can confirm this.
@shink3n Follow the Dockerfile in the root of the Repo as a starting point on how to get started with Spiderfoot from scratch.

**Comment by shink3n** [comment]
All,

I will try again, but I had both 2.7 and 3.x installed for other purposes. I am attempting to build from source. I have also tried a 16.04 and 18.04 install. I am also using google cloud platform, I’ve had some on going issues in general with pip on GCP with other installs.

I will attempt a stand alone pip3 virtual instance.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by t3chn0m4g3** [comment]
Spiderfoot is also integrated into [T-Pot](https://github.com/dtag-dev-sec/tpotce) and building using Docker works just fine. You can see in the dev channel on T-Pot (docker/spiderfoot) another example of a Dockerfile and docker-compose.yml.

**Comment by shink3n** [comment]
now receiving the following accessibility error:

 sudo python3 sf.py -l 35.227.17.9:5001
Starting web server at http://35.227.17.9:5001 ...


*************************************************************
 Use SpiderFoot by starting your web browser of choice and
 browse to http://35.227.17.9:5001
*************************************************************


[11/Mar/2020:15:31:50] ENGINE Listening for SIGTERM.
[11/Mar/2020:15:31:50] ENGINE Listening for SIGHUP.
[11/Mar/2020:15:31:50] ENGINE Listening for SIGUSR1.
[11/Mar/2020:15:31:50] ENGINE Bus STARTING
[11/Mar/2020:15:31:50] ENGINE Error in HTTP server: shutting down
Traceback (most recent call last):
  File "/home/ken/.local/lib/python3.6/site-packages/cherrypy/process/servers.py", line 225, in _start_http_thread
    self.httpserver.start()
  File "/home/ken/.local/lib/python3.6/site-packages/cheroot/server.py", line 1801, in start
    self.prepare()
  File "/home/ken/.local/lib/python3.6/site-packages/cheroot/server.py", line 1760, in prepare
    raise socket.error(msg)
OSError: No socket could be created -- (('35.227.17.9', 5001): [Errno 99] Cannot assign requested address)

[11/Mar/2020:15:31:50] ENGINE Bus STOPPING
[11/Mar/2020:15:31:50] ENGINE HTTP Server cherrypy._cpwsgi_server.CPWSGIServer(('35.227.17.9', 5001)) already shut down
[11/Mar/2020:15:31:50] ENGINE Bus STOPPED
[11/Mar/2020:15:31:50] ENGINE Bus EXITING
[11/Mar/2020:15:31:50] ENGINE Bus EXITED

I need to externally access it from my google cloud, I have added the firewall exception for 5001. UFW is disabled for now to test connection.

R/s

Ken Towne
631.747.5427
________________________________
